force-app/main/default/objects/Case/fields/caseClosedByBatch__c.field-meta.xml
<CustomField>
    <fullName>caseClosedByBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>caseClosedByBatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <formula>Contrat__r.Code_statut_contrat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code statut contrat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/toCloseDoublon__c.field-meta.xml
<CustomField>
    <fullName>toCloseDoublon__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Champ uniquement utilisé dans les batchs recouvrement pour savoir s&apos;il faut fermer la requête ou non</description>
    <label>toCloseDoublon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchContratCaseCampaignClose.cls
global class BatchContratCaseCampaignClose implements Database.Batchable<sObject>,Database.Stateful {
    global String numOfAlertCreated;
	global String numOfAlertClosed;
  List<String> listStatus = new List<String>{
    'Closed',
    'Résolue',
    'Requête déjà traitée (doublon)',
    'Fusionée'
  };
  List<String> listcodestatus = new List<String>{
    'RECAMIT',
    'RCONT',
    'RBDFT',
    'RRACRT',
    'RPPT',
    'TREG',
    'TRECAMIT',
    'TCONT'
  };

  List<Case> objToUpdate = new List<Case>();
  Id impRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName()
    .get('Gestion d’impayé')
    .getRecordTypeId();

  global Database.QueryLocator start(Database.BatchableContext bc) {

    String query =
      'SELECT Id, status,RecordTypeid, CreatedDate,caseClosedByBatch__c, toCloseDoublon__c FROM Case WHERE ' +
      'RecordTypeid=:impRecordTypeId AND ' +
      'Status NOT IN :listStatus AND ' +
      '(Code_statut_contrat__c IN :listcodestatus OR ' +
      'toCloseDoublon__c = true)';

    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext sc, List<sObject> scope) {
    List<Case> caseList = (List<Case>) scope;

    for (Case ca : caseList) {
      /*if (ca.toCloseDoublon__c) {
        ca.status = 'Requête déjà traitée (doublon)';
        objToUpdate.add(ca);
      } else {*/
        ca.status = 'Closed';
        ca.caseClosedByBatch__c = true;
        objToUpdate.add(ca);
      //}
    }
    //numOfAlertClosed = objToUpdate !=null?String.ValueOf(objToUpdate.size()):'0';
    System.debug('objToUpdate = ' + objToUpdate);
    Database.update(objToUpdate, false);
    System.debug('objToUpdate = ' + objToUpdate);
      System.debug('numOfAlertClosed = ' + numOfAlertClosed);
  }
  
  global void finish(Database.BatchableContext bc) {
        System.debug('objToUpdate = ' + objToUpdate);
        //String numOfAlertClosed = objToUpdate !=null?String.ValueOf(objToUpdate.size()):'0';
        System.debug('numOfAlertClosed:'+numOfAlertClosed);
        System.debug('numOfAlertCreated:'+numOfAlertCreated);
        //AP_FollowUpBatchAlert.sendSummary(numOfAlertCreated,numOfAlertClosed);
    }
}