force-app/main/default/objects/Case/fields/caseCreatedByBatch__c.field-meta.xml
<CustomField>
    <fullName>caseCreatedByBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <label>caseCreatedByBatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <formula>Contrat__r.Code_statut_contrat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code statut contrat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_d_ch_ance__c.field-meta.xml
<CustomField>
    <fullName>Date_d_ch_ance__c</fullName>
    <label>Date d&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_l_alerte__c.field-meta.xml
<CustomField>
    <fullName>Date_de_l_alerte__c</fullName>
    <formula>Contrat__r.Date_de_l_alerte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de l&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Administratif</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Retail</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Small Fleet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
            <value>
                <fullName>PCL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Produit_financier__c.field-meta.xml
<CustomField>
    <fullName>Produit_financier__c</fullName>
    <formula>TEXT(Contrat__r.Produit_financier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produit financier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/toCloseDoublon__c.field-meta.xml
<CustomField>
    <fullName>toCloseDoublon__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Champ uniquement utilisé dans les batchs recouvrement pour savoir s&apos;il faut fermer la requête ou non</description>
    <label>toCloseDoublon</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Gestion_d_impay.recordType-meta.xml
<RecordType>
    <fullName>Gestion_d_impay</fullName>
    <active>true</active>
    <businessProcess>FR_DefaultSupportProcess</businessProcess>
    <label>Gestion d’impayé</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <description>Code du statut du contrat</description>
    <label>Code statut contrat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Compte_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Compte_client_associe__c</fullName>
    <label>Compte client associé</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats Client</relationshipLabel>
    <relationshipName>ContratsClient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contact_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Contact_client_associe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact client associé</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact client associé)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Date_de_l_alerte__c.field-meta.xml
<CustomField>
    <fullName>Date_de_l_alerte__c</fullName>
    <description>Date de l&apos;alerte</description>
    <label>Date de l&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Produit_financier__c.field-meta.xml
<CustomField>
    <fullName>Produit_financier__c</fullName>
    <label>Produit financier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crédit</fullName>
            </value>
            <value>
                <fullName>Crédit Bail</fullName>
            </value>
            <value>
                <fullName>LLD</fullName>
            </value>
            <value>
                <fullName>LOA</fullName>
            </value>
            <value>
                <fullName>CRE</fullName>
            </value>
            <value>
                <fullName>CRV</fullName>
            </value>
            <value>
                <fullName>ASV</fullName>
            </value>
            <value>
                <fullName>CRB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchContratCaseCampaignCreate.cls
global with sharing class BatchContratCaseCampaignCreate implements Database.Batchable<sObject>,Database.Stateful {
  date dt = date.today() + 15;
  Public String numOfAlertCreatedToday;

  Recordtype impRecordTypeId = [
    SELECT id, DeveloperName
    FROM recordtype
    WHERE DeveloperName = 'Gestion_d_impay'
    LIMIT 1
  ];
  List<String> listproductRetAmiabl = new List<String>{
    'LOA',
    'CRE',
    'CRV',
    'ASV'
  };
  List<String> liststatuscodeRetAmial = new List<String>{
    'RECAMI',
    'PRECTX',
    'TAMI',
    'TPCX',
    'TRECAMI',
    'TPRECTX',
    'PTP'
  };
  List<String> listproductFletAmiabl = new List<String>{ 'LLD', 'CRB' };
  List<String> liststatuscodeFletAmial = new List<String>{
    'RECAMI',
    'PRECTX',
    'TAMI',
    'TPCX',
    'TRECAMI',
    'TPRECTX',
    'PTP'
  };
  List<String> listproductRetContet = new List<String>{
    'LOA',
    'CRE',
    'CRV',
    'ASV'
  };
  List<String> liststatuscodeRetContet = new List<String>{ 'RCONO', 'TCONO' };
  List<String> listproductFletContet = new List<String>{ 'LLD', 'CRB' };
  List<String> liststatuscodeFletContet = new List<String>{ 'RCONO', 'TCONO' };
  List<String> listproductFrenchBank = new List<String>{
    'LOA',
    'CRE',
    'CRV',
    'ASV'
  };
  List<String> liststatuscodeFrenchBank = new List<String>{
    'BDFVAL',
    'TPBDFV',
    'RBDFO',
    'BDFREC',
    'BDFNEG',
    'DDPCTX'
  };
  List<String> listproductColleProc = new List<String>{
    'LLD',
    'CRB',
    'LOA',
    'CRE',
    'ASV',
    'CRV'
  };
  List<String> liststatuscodeColleProc = new List<String>{
    'RJ',
    'LJ',
    'LA',
    'FORC',
    'MAHOC',
    'SJ',
    'RRJ',
    'RLJ',
    'RLA',
    'RMAHOC',
    'RSJ'
  };

  List<String> liststatuscoderecouv = new List<String>{
    'TAVT',
    'TFCT',
    'TSIC'
  };
 List<String> liststatuscodeLPRT = new List<String>{'LPRT'};
 List<String> listproductreamiableretailLPRT = new List<String>{
    'LOA',
    'ASV',
    'LVD',
    'SEG',
    'SEN',
    'SEP',
    'CRE'
  };
     
 List<String> listproductreamiablefleetLPRT = new List<String>{
     'LOU',
     'CBV',
     'CBP',
     'LCD',
     'LLD',
     'SMA'
  };
List<String> listproductreamiableretail = new List<String>{
    'CRV',
    'ACV',
    'LOA',
    'ASV',
    'LVD',
    'SEG',
    'SEN',
    'SEP',
    'CRE'
    
  };
 List<String> listproductreamiablefleet = new List<String>{
     'LOU',
     'CBV',
     'CBP',
     'LCD',
     'CRV',
     'LLD',
     'SMA'
  };
 List<String> liststatuscodeRecouvrementAdmin_B2F = new List<String>{
    'TNBDF',
    'TPBDF'  
  };
      
  List<Case> objToinsert = new List<Case>();
  
  global Database.QueryLocator start(Database.BatchableContext bc) {
    //system.debug('BatchContratCaseCampaign listStages : ' + listproductRetAmiabl);
    Date currentDate = Date.today();
    String query = 'SELECT Id, Produit_financier__c, CreatedDate, Code_statut_contrat__c, Date_de_l_alerte__c  FROM Contract__c WHERE ';
    query += '(((Produit_financier__c IN :listproductRetAmiabl) AND (Code_statut_contrat__c IN :liststatuscodeRetAmial)) OR ';
    query += '((Produit_financier__c IN :listproductFletAmiabl) AND (Code_statut_contrat__c IN :liststatuscodeFletAmial)) OR ';
    query += '((Produit_financier__c IN :listproductRetContet) AND (Code_statut_contrat__c IN :liststatuscodeRetContet)) OR ';
    query += '((Produit_financier__c IN :listproductFletContet) AND (Code_statut_contrat__c IN :liststatuscodeFletContet)) OR ';
    query += '((Produit_financier__c IN :listproductFrenchBank) AND (Code_statut_contrat__c IN :liststatuscodeFrenchBank)) OR ';
    query += '((Produit_financier__c IN :listproductColleProc) AND (Code_statut_contrat__c IN :liststatuscodeColleProc)) OR ';
    query += '((Produit_financier__c IN :listproductreamiableretailLPRT) AND (Code_statut_contrat__c IN :liststatuscodeLPRT)) OR ';
    query += '((Produit_financier__c IN :listproductreamiableretail) AND (Code_statut_contrat__c IN :liststatuscodeRecouvrementAdmin_B2F)) OR ';
    query += '((Produit_financier__c IN :listproductreamiableretailLPRT) AND (Code_statut_contrat__c IN :liststatuscodeLPRT)) OR ';
    query += '((Produit_financier__c IN :listproductreamiablefleetLPRT) AND (Code_statut_contrat__c IN :liststatuscodeLPRT)) OR '; 
    query += '((Produit_financier__c IN :listproductreamiablefleet) AND (Code_statut_contrat__c IN :liststatuscoderecouv)) OR ';
    query += '((Produit_financier__c IN :listproductreamiableretail) AND (Code_statut_contrat__c IN :liststatuscoderecouv)))  ';
    // system.debug('BatchOpportCreditAffecte query : ' + query);
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext sc, List<sObject> scope) {
    List<Contract__c> crtList = (List<Contract__c>) scope;
    List<Id> crtIds = new List<Id>();
    List<Case> caToUpdate = new List<Case>();
    List<Case> caseUpdated = new List<Case>();
    List<String> listStatus = new List<String>{
      'Closed',
      'Résolue',
      'Requête déjà traitée (doublon)',
      'Fusionnée'
    };

    System.debug('crtList = ' + crtList);

    //Get cases "Gestion de l'impayé" still opened that might already exist for the contracts
    List<Case> clist = [
      SELECT
        id,
        Contrat__c,
        status,
        RecordTypeId,
        Date_d_ch_ance__c,
        toCloseDoublon__c,
        Contrat__r.Date_de_l_alerte__c,
        Contrat__r.Contact_client_associe__c,
        Contrat__r.Compte_client_associe__c
      FROM case
      WHERE
        recordtypeid = :impRecordTypeId.id
        AND Contrat__c IN :crtList
        AND (NOT status IN :listStatus)
    ];
    //List to check if a case "doublon" has been already created and closed for a specific "Date de l'alerte"
    /*List<Case> clistDoublon = [
      SELECT id, Contrat__c, status, RecordTypeId, Date_d_ch_ance__c
      FROM case
      WHERE
        recordtypeid = :impRecordTypeId.id
        AND Contrat__c IN :crtList
        AND status = 'Requête déjà traitée (doublon)'
    ];*/

    AssignmentRule AR = new AssignmentRule();
    AR = [
      SELECT id
      FROM AssignmentRule
      WHERE SobjectType = 'Case' AND Active = TRUE
      LIMIT 1
    ];

    //Creating the DMLOptions for "Assign using active assignment rules" checkbox
    Database.DMLOptions dmlOpts = new Database.DMLOptions();
    dmlOpts.assignmentRuleHeader.assignmentRuleId = AR.id;

    //Check if "Date d'échéance" of the existed case is different than "Date de l'alerte" of the contract. If so, create new case with "Date d'échéance" = "Date de l'alerte"
    for (Case ca : clist) {
      crtIds.add(ca.Contrat__c);
      /*if (ca.Date_d_ch_ance__c < ca.Contrat__r.Date_de_l_alerte__c) {
        Boolean caseAlreadyExist = false;
        for (Case caseDoublon : clistDoublon) {
          if (
            ca.Contrat__c == caseDoublon.Contrat__c &&
            caseDoublon.Date_d_ch_ance__c == ca.Contrat__r.Date_de_l_alerte__c
          ) {
            caseAlreadyExist = true;
            break;
          }
        }
        if (!caseAlreadyExist) {
          Case c = new Case(
            status = 'A traiter',
            Origin = 'Gestion_d_impaye',
            recordtypeid = impRecordTypeId.id,
            Contrat__c = ca.Contrat__c,
            ContactId = ca.Contrat__r.Contact_client_associe__c,
            AccountId = ca.Contrat__r.Compte_client_associe__c,
            Date_d_ch_ance__c = ca.Contrat__r.Date_de_l_alerte__c,
            toCloseDoublon__c = true
          );
          c.setOptions(dmlOpts);
          objToinsert.add(c);
        }
      }
      if (ca.Date_d_ch_ance__c > ca.Contrat__r.Date_de_l_alerte__c) {
        Case c = new Case(
          status = 'A traiter',
          Origin = 'Gestion_d_impaye',
          recordtypeid = impRecordTypeId.id,
          Contrat__c = ca.Contrat__c,
          ContactId = ca.Contrat__r.Contact_client_associe__c,
          AccountId = ca.Contrat__r.Compte_client_associe__c,
          Date_d_ch_ance__c = ca.Contrat__r.Date_de_l_alerte__c
        );
        c.setOptions(dmlOpts);
        objToinsert.add(c);
        ca.toCloseDoublon__c = true;
        caToUpdate.add(ca);
      }*/
    }
    //Update previous case with boolean toCloseDoublon__c to close them easily
    //Database.update(caToUpdate, false);

    //Create a case for all others contracts
    for (Contract__c crt : [
      SELECT id, Contact_client_associe__c, Compte_client_associe__c
      FROM Contract__c
      WHERE id IN :crtList AND id NOT IN :crtIds
    ]) {
      Case c = new Case(
        status = 'A traiter',
        Origin = 'Gestion_d_impaye',
        recordtypeid = impRecordTypeId.id,
        Contrat__c = crt.id,
        ContactId = crt.Contact_client_associe__c,
        AccountId = crt.Compte_client_associe__c,
        caseCreatedByBatch__c = True,
        Date_d_ch_ance__c = dt
      );
      /*if (crt.Date_de_l_alerte__c != null)
        c.Date_d_ch_ance__c = crt.Date_de_l_alerte__c;
      else
        c.Date_d_ch_ance__c = dt;*/

      c.setOptions(dmlOpts);
      objToinsert.add(c);
    }

    //numOfAlertCreatedToday = objToinsert != null ? String.ValueOf(objToinsert.size()):'0';
    Database.insert(objToinsert, false);

    //Remplissage de l'équipe et motif en fonction de la file d'attente
    List<id> idCase = new List<id>();
    for (Case myCase : objToinsert) {
      idCase.add(myCase.Id);
    }
    List<Case> caseToUpdate = [
      SELECT id, Service__c, Equipe__c, Motif__c
      FROM Case
      WHERE Id IN :idCase
    ];
    for (Case c : caseToUpdate) {
      String nameOwner = c.Service__c;
      if (nameOwner != null && (c.equipe__c == null || c.motif__c == null)) {
        if (nameOwner.contains('RETAIL')) {
          c.equipe__c = 'Recouvrement - Retail';
        }
        if (nameOwner.contains('FLEET')) {
          c.equipe__c = 'Recouvrement - Small Fleet';
        }
        if (
          nameOwner.contains('AMIABLE') ||
          nameOwner.contains('IPTR') ||
          nameOwner.contains('STAND ALONE')
        ) {
          c.motif__c = 'Amiable';
        }
        if (nameOwner.contains('CTX') || nameOwner.contains('DDPCTX')) {
          c.motif__c = 'Contentieux';
        }
        if (nameOwner.contains('BDF')) {
          c.equipe__c = 'Recouvrement - Administratif';
          c.motif__c = 'Banque de France';
        }
        if (nameOwner.contains('PCL')) {
          c.equipe__c = 'Recouvrement - Small Fleet';
          c.motif__c = 'PCL';
        }
      }
      caseUpdated.add(c);
    }
    try {
      update caseUpdated;
    } catch (Exception e) {
      System.debug('error = ' + e);
    }
  }

  global void finish(Database.BatchableContext bc) {
      System.debug('objToinsert size:'+objToinsert.size());
     // BatchContratCaseCampaignClose closeAlert = new BatchContratCaseCampaignClose();
      //closeAlert.numOfAlertCreated = numOfAlertCreatedToday;//objToinsert != null ? String.ValueOf(objToinsert.size()):'0';
      Database.executeBatch(new BatchContratCaseCampaignClose(), 1000);
  }
}