force-app/main/default/objects/Case/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_motif__c.field-meta.xml
<CustomField>
    <fullName>Sous_motif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acte de décès</fullName>
            </value>
            <value>
                <fullName>Ajout/suppression de prestation</fullName>
            </value>
            <value>
                <fullName>Ajout/Suppression prestation</fullName>
            </value>
            <value>
                <fullName>Ajout de prestation</fullName>
            </value>
            <value>
                <fullName>Alerte futur impayé</fullName>
            </value>
            <value>
                <fullName>Amende</fullName>
            </value>
            <value>
                <fullName>AND/AEN</fullName>
            </value>
            <value>
                <fullName>ANTS - Fin de Contrat</fullName>
            </value>
            <value>
                <fullName>ANTS - Fins de Contrat</fullName>
            </value>
            <value>
                <fullName>Appel pour l&apos;acceptation</fullName>
            </value>
            <value>
                <fullName>Appel pour le paiement</fullName>
            </value>
            <value>
                <fullName>Appel pour les RC</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>Assistance 1er loyer</fullName>
            </value>
            <value>
                <fullName>Assistance outils</fullName>
            </value>
            <value>
                <fullName>Assistance virement</fullName>
            </value>
            <value>
                <fullName>Assitance 1er loyer</fullName>
                <isActive>false</isActive>
                <label>Assitance 1er loyer</label>
            </value>
            <value>
                <fullName>Attestation de fin de contrat</fullName>
            </value>
            <value>
                <fullName>Attestation fin de contrat</fullName>
            </value>
            <value>
                <fullName>AUCUN</fullName>
                <isActive>false</isActive>
                <label>AUCUN</label>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
            <value>
                <fullName>Avenant de transfert</fullName>
            </value>
            <value>
                <fullName>Avis de citation à partie civile</fullName>
            </value>
            <value>
                <fullName>Avis de classement à victime</fullName>
            </value>
            <value>
                <fullName>Carte carburant</fullName>
            </value>
            <value>
                <fullName>Carte grise</fullName>
            </value>
            <value>
                <fullName>Carte grise - cession</fullName>
            </value>
            <value>
                <fullName>Carte grise - demande démarche</fullName>
            </value>
            <value>
                <fullName>Carte grise - en cours de contrat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ExternalRoleSharingConfig__mdt/ExternalRoleSharingConfig__mdt.object-meta.xml
<CustomObject>
    <label>ExternalRoleSharingConfig</label>
    <pluralLabel>ExternalRoleSharingConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - RC</fullName>
            </value>
            <value>
                <fullName>Paiement Fleet</fullName>
            </value>
            <value>
                <fullName>Paiement Grands comptes</fullName>
            </value>
            <value>
                <fullName>Paiement Manuel</fullName>
            </value>
            <value>
                <fullName>Paiement régularisation</fullName>
            </value>
            <value>
                <fullName>Paiement Retail</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB divers</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB réclamations</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Administratif et Banque de France</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Affaires Spéciales</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Fleet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailMessageTriggerHandler.cls
public with sharing class EmailMessageTriggerHandler {
  public static void handleTrigger(
    List<EmailMessage> emailList,
    System.TriggerOperation triggerEvent
  ) {
    switch on triggerEvent {
      when AFTER_INSERT {
        //handleAfterInsert(emailList);
      }
      when BEFORE_INSERT {
        handleBeforeInsert(emailList);
      }
    }
  }

  public static void handleBeforeInsert(List<EmailMessage> emailList) {
    System.debug('######emailList:' + emailList);

    List<Case> caseList = [
      SELECT
        Id,
        OwnerId,
        Status,
        IsClosed,
        Origin,
        Equipe__c,
        Motif__c,
        Sous_motif__c,
        ContactId,
        Contrat__c,
        AccountId,
        CreatedById
      FROM Case
      WHERE id = :emailList[0].parentId
      LIMIT 1
    ];
    System.debug('######caseList:' + caseList);
    Case newCase = new Case();
    Id ownerIdQueuorUser;
    if (caseList.size() > 0) {
      ownerIdQueuorUser = caseList[0].OwnerId;
    }
    List<ExternalRoleSharingConfig__mdt> allowedQueues = [
      SELECT Id, Label
      FROM ExternalRoleSharingConfig__mdt
    ];
    Set<Id> userIdstoAllows = new Set<Id>();
    Set<Id> queuesIdstoAllows = new Set<Id>();

    System.debug('######ownerIdQueuorUser:' + ownerIdQueuorUser);
    List<User> myUser = [
      SELECT id, UserRoleId, Equipe__c
      FROM USER
      WHERE id = :ownerIdQueuorUser
    ];
    System.debug('myUser:' + myUser);
    //2533
    Id extAgentRleId;
    Id extSuperviseurRleId;
    List<UserRole> extRoleList = [
      SELECT Id, Name
      FROM UserRole
      WHERE Name = 'agent_RC_ext' OR Name = 'superviseur_RC_ext'
    ];
    System.debug('extRoleList:' + extRoleList);
    for (UserRole usr : extRoleList) {
      if (usr.Name == 'agent_RC_ext') {
        extAgentRleId = usr.Id;
      } else if (usr.Name == 'superviseur_RC_ext') {
        extSuperviseurRleId = usr.Id;
      }
    }
    List<Profile> Profiles = [SELECT Id, Name FROM Profile];
    System.debug('Profiles:' + Profiles);
    Id SystemAdminProfileId;
    Id TechRef360Id;
    for (Profile p : Profiles) {
      if (p.Name == 'System Administrator') {
        SystemAdminProfileId = p.Id;
      } else if (p.Name == 'TechRef360') {
        TechRef360Id = p.Id;
      }
    }
    String uRoleId = UserInfo.getUserRoleId();
    system.debug('uRoleId:' + uRoleId);
    Boolean isUserOrQueue = false;
    Id connectedUserId = UserInfo.getUserId();
    System.debug('######connectedUserId:' + connectedUserId);
    Set<Id> roleRelatedId = new Set<Id>();
    Set<Id> parentRoleId = new Set<Id>();
    Set<Id> groupMembersId = new Set<Id>();
    if (myUser.size() < 1) {
      List<Group> myQueue = [
        SELECT id, Related.Name, Name
        FROM Group
        WHERE id = :ownerIdQueuorUser
      ];
      //Group myQueue = [SELECT id,RelatedId,Related.Name from Group where RelatedId=:uRoleId and type='Role'][0];
      System.debug('myQueue:' + myQueue);

      List<GroupMember> grpMembers = [
        SELECT Id, UserOrGroupId
        FROM GroupMember
        WHERE GroupId = :myQueue[0].Id
      ];
      System.debug('grpMembers:' + grpMembers);
      for (GroupMember gpM : grpMembers) {
        groupMembersId.add(gpM.UserOrGroupId);
      }
      system.debug('groupMembersId:' + groupMembersId);
      List<Group> getRoleInQueue = [
        SELECT id, Related.Name, RelatedId
        FROM Group
        WHERE id IN :groupMembersId
      ];
      for (Group gp : getRoleInQueue) {
        roleRelatedId.add(gp.RelatedId);
      }
      System.debug('getRoleInQueue:' + getRoleInQueue);
      system.debug('roleRelatedId:' + roleRelatedId);
      List<UserRole> parentRole = [
        SELECT Id, ParentRoleId
        FROM UserRole
        WHERE Id IN :roleRelatedId
      ];
      System.debug('parentRole:' + parentRole);
      for (UserRole usr : parentRole) {
        parentRoleId.add(usr.ParentRoleId);
      }
      system.debug('parentRoleId:' + parentRoleId);
      system.debug('parentRole:' + parentRole);
      List<UserRole> getAllChildRole = [
        SELECT Id, ParentRoleId
        FROM UserRole
        WHERE
          ParentRoleId IN :parentRoleId
          OR ParentRoleId IN :roleRelatedId
          OR Id IN :parentRoleId
          OR Id IN :roleRelatedId
      ];
      System.debug('getAllChildRole:' + getAllChildRole);

      for (UserRole rle : getAllChildRole) {
        if (rle.Id == uRoleId) {
          isUserOrQueue = true;
        }
      }
      //2533
      if (
        UserInfo.getUserRoleId() == extAgentRleId ||
        UserInfo.getUserRoleId() == extSuperviseurRleId
      ) {
        for (Group grp : myQueue) {
          for (ExternalRoleSharingConfig__mdt ext : allowedQueues) {
            if (grp.Name == ext.Label) {
              queuesIdstoAllows.add(grp.Id);
            }
          }
        }
      }
    }

    if (
      UserInfo.getUserRoleId() == extAgentRleId ||
      UserInfo.getUserRoleId() == extSuperviseurRleId
    ) {
      for (User usr : myUser) {
        for (ExternalRoleSharingConfig__mdt ext : allowedQueues) {
          if (usr.Equipe__c == ext.Label) {
            userIdstoAllows.add(usr.Id);
          }
        }
      }
    }
    if (myUser.size() > 0 && myUser[0].Id == connectedUserId) {
      isUserOrQueue = true;
    }

    if (
      UserInfo.getProfileId() == SystemAdminProfileId ||
      UserInfo.getProfileId() == TechRef360Id ||
      UserInfo.getUserRoleId() == extAgentRleId ||
      UserInfo.getUserRoleId() == extSuperviseurRleId ||
      UserInfo.getLastName() == 'System'
    ) {
      isUserOrQueue = true;
    }
    if (isUserOrQueue == false) {
      emailList[0]
        .id.addError('Vous n\'êtes pas autorisé à envoyer des emails ');
    }

    //2533
    system.debug('queuesIdstoAllows:' + queuesIdstoAllows);
    system.debug('userIdstoAllows:' + userIdstoAllows);
    if (
      UserInfo.getUserRoleId() == extAgentRleId ||
      UserInfo.getUserRoleId() == extSuperviseurRleId
    ) {
      for (EmailMessage EM : emailList) {
        Boolean displayError = true;
        if (queuesIdstoAllows.size() > 0) {
          for (Id ids : queuesIdstoAllows) {
            if (caseList[0].ownerId == ids) {
              displayError = false;
            }
          }
        }
        if (userIdstoAllows.size() > 0) {
          for (Id ids : userIdstoAllows) {
            if (caseList[0].ownerId == ids) {
              displayError = false;
            }
          }
        }
        if (displayError == true) {
          EM.addError(System.label.extRleEmailRestrictionError);
        }
      }
    }
    // developpement 2597
    /*if (caseList.size() > 0) {
      if (caseList[0].Status == 'Résolue' 
         || caseList[0].Status == 'Absence de retour client'
         || caseList[0].Status == 'Absence de retour partenaire'
         || caseList[0].Status == 'Requête déjà traitée (doublon)'
         || caseList[0].Status == 'Requête annulée (le client ne souhaite pas donner suite)'
         || caseList[0].Status == 'Erreur destinataire'
         || caseList[0].Status == 'Opportunité commerciale') {
        try {
          String sObjName = caseList[0]
            .OwnerId.getSObjectType()
            .getDescribe()
            .getName();
          if (sObjName != 'User') {
            List<Group> currentGroup = [
              SELECT Id, Name
              FROM Group
              WHERE Id = :caseList[0].OwnerId
            ];
            system.debug('currentGroup :' + currentGroup);

            system.debug('enter AP_SendEMail');
            system.debug('group Name:' + currentGroup[0].Name);
            system.debug('ValidatedFromAddress:' + emailList[0].ValidatedFromAddress); 
            system.debug('FromAddress :' + emailList[0].FromAddress);
            AP_SendEMail.autoReply(
              currentGroup[0].Name,
              emailList[0].FromAddress
            );
            system.debug('after AP_SendEMail');
          }
          //emailList[0].addError('You cannot send email to or from a closed case');
        } catch (Exception e) {
          system.debug('error :' + e.getMessage());
        }
      }
    } */

    //Début partie gestion parent case
    EmailMessage emsg = emailList.get(0);
    String emsgSubjectBody = emsg.Subject + ' ' + emsg.TextBody;
    System.debug('emsg = ' + emsg);
    System.debug('emsgSubjectBody = ' + emsgSubjectBody);

    newCase = ParentCase.getParentCaseId(newCase, emsg);
    
    Pattern myPatternThreadId = Pattern.compile('ref:.*:ref ');
    Matcher myMatcherThreadId = myPatternThreadId.matcher(emsgSubjectBody);
    Boolean myMatcherThreadIdBoolean = myMatcherThreadId.find();
    System.debug('matcher threadId = ' + myMatcherThreadIdBoolean);
    System.debug('parent case isClosed = ' + ParentCase.parentCaseIsClosed);
    System.debug('emsg.Incoming = ' + emsg.Incoming);

    if (emsg.Incoming && (myMatcherThreadIdBoolean || ParentCase.parentCaseIsClosed)) {
      System.debug('Dans le if création newCase');
      newCase.Subject = emsg.Subject;
      newCase.Equipe__c = caseList[0].Equipe__c;
      newCase.Motif__c = caseList[0].Motif__c;
      newCase.Sous_motif__c = caseList[0].Sous_motif__c;
      newCase.Origin = caseList[0].Origin;
      //Si requête parent avec un ancien thread id détecté, on ouvre une nouvelle requête
      if (myMatcherThreadIdBoolean) {
        insert newCase;
      } else {
        newCase.Id = emsg.parentId;
      }
      //Rajouter un try pour ne pas bloquer l'exécution du code en cas de problème. Ex : automated process ne peut pas accéder à l'api chatter donc ne peut pas poser de message dans le feed
      //Contournement : mettre un utilisateur admin dans Support Settings > Automated Case User
      try {
        if (ParentCase.parentCaseIsClosed) {
          String newCaseIdString = Id.valueOf(newCase.Id);
          String OwnerIdString = Id.valueOf(newCase.OwnerId);
          if (OwnerIdString.startsWith('005')) {
            ConnectApiHelper.postFeedItemWithMentions(
                null,
                newCaseIdString,
                '{' +
                OwnerIdString +
                '}' +
                ' Nouvelle requête créée depuis une requête fermée (voir requête Parent dans détail)'
            );
          } else {
              ConnectApiHelper.postFeedItemWithMentions(
                  null,
                  newCaseIdString, 
                  'Nouvelle requête créée depuis une requête fermée (voir requête Parent dans détail)'
                );
          }
        }
      } catch (Exception e) {
        System.debug('erreur post message requête créée depuis une requête fermée : ' + e);
      }
        
      emsg.ParentId = newCase.Id;
    } else {
      newCase.Id = emsg.parentId;
    }
    System.debug('newCase = ' + newCase);
    if (ParentCase.newParentChildFamily) {
      Pattern patternEmailInReplyTo = Pattern.compile('In-Reply-To: <.*>');
      Matcher matcherEmailInReplyTo = patternEmailInReplyTo.matcher(emsg.Headers);

      Pattern patternEmailReference = Pattern.compile('References:.*');
      Matcher matcherEmailReference = patternEmailReference.matcher(emsg.Headers);

      if (matcherEmailInReplyTo.find() && matcherEmailReference.find()) {
        String inReplyTo = emsg.Headers.substringBetween('In-Reply-To: <', '>');
        inReplyTo = '<' + inReplyTo + '>';

        String textToReplace = emsg.Headers.substringBetween('References:', inReplyTo);
        System.debug('textToReplace = ' + textToReplace);

        List<String> listEmailParentCase = emsg.Headers.split('<');
        System.debug('listEmailParentCase = ' + listEmailParentCase);

        try {
          String emailParentCase =  '<' + listEmailParentCase[listEmailParentCase.size()-2];
          emsg.Headers = emsg.Headers.replace(textToReplace, emailParentCase);
          System.debug('emsg.Headers = ' + emsg.Headers);
          
        } catch (Exception e) {
          System.debug(e);
        }

      }
    }

    if (emailList.size() != 1 || !emailList?.get(0)?.incoming)
      return;

    try {
      newCase = KeywordDetection.rulesMatcher(emsg, newCase);

      //getting the contact
      /*String email = emsg.FromAddress;
      if (String.isNotBlank(email)) {
        List<Profile> profileId = [
          SELECT Id
          FROM Profile
          WHERE Name = 'Manager' OR Name LIKE 'Agent%'
          ];
          List<User> user = [
            SELECT Id
            FROM User
            WHERE Email LIKE :email AND ProfileId IN :profileId
            LIMIT 1
            ];
        if (user.isEmpty()) {
          List<List<SObject>> searchResult = [
            FIND :email
            IN EMAIL FIELDS
            RETURNING Contact(id, AccountId)
            ];
            if (
              searchResult != null &&
              !searchResult.isEmpty() &&
              searchResult.get(0) != null &&
              !searchResult.get(0).isEmpty() &&
              searchResult.get(0).get(0) != null
              ) {
                Contact ctc = (Contact) searchResult.get(0).get(0);
                newCase.ContactId = ctc.Id;
                newCase.AccountId = ctc.AccountId;
              }
            }
          }*/

      String resultatDetection = ImmatOuNumContratDetection.immatContratDetection(
        emsgSubjectBody
      );
      System.debug('resultatDetection : ' + resultatDetection);
      Contract__c ctr;
      if (String.isNotBlank(resultatDetection)) {
        ctr = ImmatOuNumContratDetection.linkContrat(resultatDetection);
        if (ctr != null) {
          newCase.Contrat__c = ctr.Id;
          System.debug('ctr : ' + ctr);
        }
      }
      System.debug('newCase 2 = ' + newCase);
      update newCase;
      Case contactCase = [
        SELECT Id, ContactId, SuppliedEmail
        FROM Case
        WHERE Id = :newCase.Id
      ];
      if (contactCase.ContactId != null) {
        List<Profile> profileId = [
          SELECT Id
          FROM Profile
          WHERE Name = 'Manager' OR Name LIKE 'Agent%'
        ];
        List<User> user = [
          SELECT Id
          FROM User
          WHERE
            Email LIKE :contactCase.SuppliedEmail
            AND ProfileId IN :profileId
          LIMIT 1
        ];
        if (!user.isEmpty()) {
          newCase.ContactId = '';
          newCase.AccountId = '';
          update newCase;
        }
      }
    } catch (Exception e) {
      System.debug(
        e.getTypeName() +
        '\n' +
        e.getMessage() +
        '\n' +
        e.getStackTraceString()
      );
    }
  }

  /*public static void handleAfterInsert(List<EmailMessage> emailList) {
      Map<Id,EmailMessage> caseIdEmailMessage = new Map<Id,EmailMessage>();
      Boolean isClient = true;
      Boolean doNotDelEmail = false;
      List<Case> caseList = [
      SELECT
        Id,
        OwnerId,
        Status,
        Equipe__c,
        Motif__c,
        Sous_motif__c,
        ContactId,
        Contrat__c,
        AccountId,
        CreatedById
      FROM Case
      WHERE id = :emailList[0].parentId
      LIMIT 1
      ];
      System.debug('caseList :' + caseList);
      
      for(EmailMessage em : emailList){
              caseIdEmailMessage.put(em.ParentId,em);
      }
        List<QueueOrUserEmail__mdt> queuesEmailList = [SELECT Id,usedForAtraiter__c,Email__c FROM QueueOrUserEmail__mdt WHERE usedForAtraiter__c = True];
      
      for(QueueOrUserEmail__mdt mdt : queuesEmailList){
        if(emailList[0].FromAddress == mdt.Email__c){
          isClient = false;
        }
      }
      if (caseList.size() > 0 && isClient) {
        if (caseList[0].Status == 'En attente') {
          caseList[0].Status = 'A traiter';
          update caseList[0];
        }
      }
        List<QueueOrUserEmail__mdt> queuesEmailList2 = [SELECT Id,UsedForNoReply__c,Email__c FROM QueueOrUserEmail__mdt WHERE UsedForNoReply__c = True];
      for(QueueOrUserEmail__mdt queuesEm : queuesEmailList2){
        if(emailList[0].FromAddress == queuesEm.Email__c){
          doNotDelEmail = true;
        }
      }
      if (caseList.size() > 0) {
        if ((caseList[0].Status == 'Résolue' 
          || caseList[0].Status == 'Absence de retour client'
          || caseList[0].Status == 'Absence de retour partenaire'
          || caseList[0].Status == 'Requête déjà traitée (doublon)'
          || caseList[0].Status == 'Requête annulée (le client ne souhaite pas donner suite)'
          || caseList[0].Status == 'Erreur destinataire'
          || caseList[0].Status == 'Opportunité commerciale') && !doNotDelEmail) {
          deleteEmailMessage(new List<Id>{caseIdEmailMessage.get(caseList[0].Id).Id});
        }
      } 
    }
     @future
    public static void deleteEmailMessage(List<Id> emailMssgId) {
      List<EmailMessage> emailMssg =[SELECT Id FROM EmailMessage WHERE Id =:emailMssgId];
      Delete emailMssg;
    } 
    
    */
}