force-app/main/default/objects/Case/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Requ_te_standard.recordType-meta.xml
<RecordType>
    <fullName>Requ_te_standard</fullName>
    <active>true</active>
    <businessProcess>FR_DefaultSupportProcess</businessProcess>
    <label>Requête standard</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Compte_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Compte_client_associe__c</fullName>
    <label>Compte client associé</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats Client</relationshipLabel>
    <relationshipName>ContratsClient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contact_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Contact_client_associe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact client associé</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact client associé)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Immatriculation__c.field-meta.xml
<CustomField>
    <fullName>Immatriculation__c</fullName>
    <externalId>true</externalId>
    <label>Immatriculation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Numero_de_chassis__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_chassis__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de châssis</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Numero_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_contrat__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de contrat</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - RC</fullName>
            </value>
            <value>
                <fullName>Paiement Fleet</fullName>
            </value>
            <value>
                <fullName>Paiement Grands comptes</fullName>
            </value>
            <value>
                <fullName>Paiement Manuel</fullName>
            </value>
            <value>
                <fullName>Paiement régularisation</fullName>
            </value>
            <value>
                <fullName>Paiement Retail</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB divers</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB réclamations</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Administratif et Banque de France</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Affaires Spéciales</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Fleet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FormsEmailHandler_TEST.cls
@isTest
public class FormsEmailHandler_TEST {
  @isTest
  static void test1() {
    Recordtype rtcaseid = [
      SELECT id, DeveloperName
      FROM recordtype
      WHERE DeveloperName = 'Requ_te_standard'
      LIMIT 1
    ];
    Account a = new Account(Name = 'account');
    insert a;
    Contact ctc = new Contact(
      firstName = 'John',
      lastName = 'Doe',
      email = 'john@doe.com'
    );

    insert ctc;

    Contract__c ctra = new Contract__c();
    ctra.Numero_de_contrat__c = '98987000LOA0';
    ctra.Immatriculation__c = 'AB-123-CD';
    ctra.Name = '98987000LOA0';
    ctra.Compte_client_associe__c = a.Id;
    ctra.Contact_client_associe__c = ctc.Id;
    insert ctra;

    Contract__c ctra2 = new Contract__c();
    ctra2.Numero_de_contrat__c = '98989000LOA0';
    ctra2.Name = '98989000LOA0';
    ctra2.Compte_client_associe__c = a.Id;
    ctra2.Contact_client_associe__c = ctc.Id;
    insert ctra2;

    Contract__c ctra3 = new Contract__c();
    ctra3.Numero_de_contrat__c = '96989000LOA0';
    ctra3.Numero_de_chassis__c = 'ABCDEFGHIJKLMN123';
    ctra3.Name = '96989000LOA0';
    ctra3.Compte_client_associe__c = a.Id;
    ctra3.Contact_client_associe__c = ctc.Id;
    insert ctra3;

    Case c0 = new Case();
    c0.Subject = 'ctr Test';
    c0.Status = 'Closed';
    c0.Contrat__c = ctra.id;
    c0.RecordTypeId = rtcaseid.id;
    c0.ContactId = ctra.Contact_client_associe__c;
    c0.AccountId = a.id;
    c0.Priority = 'Low';
    c0.Origin = 'Email';
    c0.Equipe__c = 'Acceptation Annexes';
    c0.Motif__c = 'Divers';
    insert c0;

    Test.startTest();
    Messaging.Inboundemail.TextAttachment att = new Messaging.Inboundemail.TextAttachment();
    ContentVersion cVersions = new ContentVersion();
    cVersions.title = 'Test title';
    cVersions.VersionData = blob.valueof('New Bitmap Image.bmp');
    cVersions.ContentLocation = 'S';
    cVersions.Origin = 'H';
    cVersions.PathOnClient = 'ContentAgreement1.pdf';

    insert cVersions;
    /*ContentDocumentLink cdl = new ContentDocumentLink( LinkedEntityId = c0.Id, ShareType= 'V');
     insert cdl;*/

    ContentDocumentLink contentlink = new ContentDocumentLink();
    contentlink.LinkedEntityId = c0.id;
    contentlink.contentdocumentid = [
      SELECT contentdocumentid
      FROM contentversion
      WHERE id = :cVersions.id
    ]
    .contentdocumentid;
    contentlink.ShareType = 'I';
    contentlink.Visibility = 'AllUsers';

    insert contentlink;
    Test.setFixedSearchResults(new List<Id>{ ctc.id });

    Messaging.InboundEmail email = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env = new Messaging.InboundEnvelope();
    email.subject = 'RE: Autorisation de prélèvement de solde 12345678LLD0';
    email.toAddresses = (new List<String>{ 'web@forms.com' });
    env.fromAddress = 'user@acme.com';

    email.plainTextBody = 'Autorisation de prélèvement de solde\nNuméro de contrat : 98989000LOA\nCivilité : Mme.\nNom : KARACA\nPrénom : SUKRIYE\nDate de naissance : 22/08/1983\nE-mail : karacasukriye@hotmail.fr\nNuméro de téléphone portable : 0613872786\nMarque Véhicule : Volkswagen\n\nJe soussigné(e) : SUKRIYE KARACA\nNuméro de contrat : 98989000LOA\nMontant du solde : 2528.73\n\nMotif du solde : Revente du véhicule\nPrécision réponse \"autre\" :';

    Messaging.InboundEmail email1 = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env1 = new Messaging.InboundEnvelope();
    email1.subject = 'RE: Autorisation de prélèvement de solde test AB-123-CD';
    email1.toAddresses = (new List<String>{ 'web@forms.com' });
    env1.fromAddress = 'useracme.com';

    email1.plainTextBody = 'xml "é"A \nNuméro de contrat : AB-123-CD';

    Messaging.InboundEmail email2 = new Messaging.InboundEmail();
    Messaging.InboundEnvelope env2 = new Messaging.InboundEnvelope();
    email2.subject = 'RE: Autorisation de prélèvement de solde test ABCDEFGHIJKLMN123';
    email2.toAddresses = (new List<String>{ 'web@forms.com' });
    env2.fromAddress = 'useracme.com';

    email2.plainTextBody = 'Numéro de contrat : ABCDEFGHIJKLMN123';

    (new FormsEmailHandler()).handleInboundEmail(email, env);
    (new FormsEmailHandler()).handleInboundEmail(email1, env1);
    (new FormsEmailHandler()).handleInboundEmail(email2, env2);

    System.assertEquals([SELECT id FROM case].isEmpty(), false);
    System.assertEquals([SELECT id FROM EmailMessage].isEmpty(), false);
    System.assertEquals(
      [SELECT ContentDocumentId, id FROM ContentVersion].isEmpty(),
      false
    );

    Test.stopTest();
  }
}