force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Tempspassenfiledattente__c.field-meta.xml
<CustomField>
    <fullName>Tempspassenfiledattente__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Temps passés en file d&apos;attente(en jours)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tempspassepourtraitement__c.field-meta.xml
<CustomField>
    <fullName>Tempspassepourtraitement__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Temps passés pour traitement(en jours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Tempspasssenstatutdattentejour__c.field-meta.xml
<CustomField>
    <fullName>Tempspasssenstatutdattentejour__c</fullName>
    <defaultValue>0</defaultValue>
    <description>US:P002156-1609</description>
    <label>Temps passés en statut d&apos;attente(jour)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ExternalRoleSharingConfig__mdt/ExternalRoleSharingConfig__mdt.object-meta.xml
<CustomObject>
    <label>ExternalRoleSharingConfig</label>
    <pluralLabel>ExternalRoleSharingConfig</pluralLabel>
</CustomObject>

force-app/main/default/objects/User/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - RC</fullName>
            </value>
            <value>
                <fullName>Paiement Fleet</fullName>
            </value>
            <value>
                <fullName>Paiement Grands comptes</fullName>
            </value>
            <value>
                <fullName>Paiement Manuel</fullName>
            </value>
            <value>
                <fullName>Paiement régularisation</fullName>
            </value>
            <value>
                <fullName>Paiement Retail</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB divers</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB réclamations</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Administratif et Banque de France</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Affaires Spéciales</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Fleet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**
 * @author Yves RUMURI
 * @date Creation 10/05/2021
 * @description CaseTrigger
 * Ver   Date         Author                               Modification
 * 1.0   10-05-2021   YRU                             Initial Version [P002156-1609]
 */
public with sharing class CaseTriggerHandler {
  public static void handleTrigger(
      List<Case> caseList,
      System.TriggerOperation triggerEvent,
      Map<Id,Case> oldMap,
      Map<Id,Case> newMap
  ) {
      switch on triggerEvent {
          when BEFORE_UPDATE {
              handleBeforeUpdate(oldMap,newMap);
          }
    when AFTER_INSERT {
    }
    when AFTER_UPDATE {
      if (checkRecursive.firstcall) {
        checkRecursive.firstcall = false;
        handleAfterUpdate(caseList);
      }
    }
  }
}
  
  public static void handleBeforeUpdate(Map<Id,Case> oldMap,Map<Id,Case> newMap) {
      Set<Id> caseOwnerIdSet = new Set<Id>();
      Set<Id> userIdstoAllows = new Set<Id>();
      Set<Id> queuesIdstoAllows = new Set<Id>();
      Id extAgentRleId;
      Id extSuperviseurRleId;
      List<ExternalRoleSharingConfig__mdt> allowedQueues = [SELECT Id,Label FROM ExternalRoleSharingConfig__mdt];
      System.debug('allowedQueues:'+allowedQueues);
      List<UserRole> extRoleList = [SELECT Id,Name FROM UserRole WHERE (Name='agent_RC_ext' OR Name='superviseur_RC_ext')];
      System.debug('extRoleList:'+extRoleList);
      for(UserRole usr : extRoleList){
          if(usr.Name == 'agent_RC_ext'){
              extAgentRleId = usr.Id;
          }else if(usr.Name == 'superviseur_RC_ext'){
              extSuperviseurRleId = usr.Id;
          }  
      }
      System.debug('extAgentRleId:'+extAgentRleId);
      System.debug('extSuperviseurRleId:'+extSuperviseurRleId);
      if(UserInfo.getUserRoleId()==extAgentRleId || UserInfo.getUserRoleId()==extSuperviseurRleId){
          for(Id ids : newMap.keyset()){
               caseOwnerIdSet.add(newMap.get(ids).ownerId);
          }
      }
      System.debug('caseOwnerIdSet:'+caseOwnerIdSet);
      List<User> caseOwnerUser = [SELECT id,UserRoleId,Equipe__c from USER where id =:caseOwnerIdSet];
      System.debug('caseOwnerUser:'+caseOwnerUser);
      if(caseOwnerUser.size()>0){
          for(User usr : caseOwnerUser){
              for(ExternalRoleSharingConfig__mdt ext : allowedQueues){
                  if(usr.equipe__c == ext.Label){
                      userIdstoAllows.add(usr.Id); 
                  }  
              }
          }
      }
      System.debug('userIdstoAllows:'+userIdstoAllows);
      List<Group> myQueues = [SELECT id,Name from Group where id =:caseOwnerIdSet];
      if(myQueues.size()>0){
          for(Group que : myQueues){
              for(ExternalRoleSharingConfig__mdt ext : allowedQueues){
                  if(que.Name == ext.Label){
                      queuesIdstoAllows.add(que.Id); 
                  }
              }
          }
      }
      System.debug('queuesIdstoAllows:'+queuesIdstoAllows);
      if(caseOwnerIdSet.size()>0){
          for(Case cs : newMap.values()){
              Boolean displayError = true;
              if(userIdstoAllows.size()>0){
                  for(Id ids : userIdstoAllows){
                      if(cs.OwnerId == ids){
                          displayError = false;
                      }
                  }
              }
              if(queuesIdstoAllows.size()>0){
                  for(Id ids : queuesIdstoAllows){
                      System.debug('OwnerId:'+cs.OwnerId);
                      system.debug('ids:'+ids);
                      if(cs.OwnerId == ids){
                          system.debug('enter if ');
                          displayError = false;
                          system.debug('displayError');
                      }
                  }
              }
              if(displayError == true){
                  cs.addError(System.label.extRoleRestrictionError);
              }
          }  
      }
      ParentCase.caseUpdate(oldMap, newMap);
  }
public static void handleAfterInsert(List<Case> caseList) {
 
}

public static void handleAfterUpdate(List<Case> caseList) {
    
    List<Id> idList = new List<Id>();
    for(Case cs : caseList){
        idList.add(cs.id);
    }
    
  List<case> caseup = [
    SELECT
      Id,
      OwnerId,
      status,
      IsClosed,
      ParentId,
      Tempspassenfiledattente__c,
      Tempspasssenstatutdattentejour__c,
      Tempspassepourtraitement__c,
      CreatedDate,
      ClosedDate
    FROM case
    WHERE id IN :caseList
  ];
  List<casehistory> casehistorOwner = [
    SELECT
      Id,
      case.Tempspasssenstatutdattentejour__c,
      case.Tempspassenfiledattente__c,
      case.Tempspassepourtraitement__c,
      case.closeddate,
      case.Owner.Type,
      caseid,
      newvalue,
      oldvalue,
      field,
      createddate
    FROM casehistory
    WHERE caseid IN :caseup AND field = 'Owner'
    ORDER BY createddate ASC
  ];

  List<casehistory> casehistorStat = [
    SELECT
      Id,
      case.Tempspassenfiledattente__c,
      case.Tempspassepourtraitement__c,
      case.Tempspasssenstatutdattentejour__c,
      case.closeddate,
      case.Owner.Type,
      caseid,
      newvalue,
      oldvalue,
      field,
      createddate
    FROM casehistory
    WHERE caseid IN :caseup AND field = 'Status'
    ORDER BY createddate ASC
  ];

  List<Group> Queue = [SELECT id FROM Group WHERE Type = 'Queue'];
  List<id> idQueue = new List<id>();
  for (Group qu : Queue) {
    idQueue.add(qu.id);
  }

  List<User> User = [SELECT id FROM User];
  List<id> idUser = new List<id>();
  for (User us : User) {
    idUser.add(us.id);
  }

  BusinessHours bh = [SELECT id FROM businesshours WHERE IsDefault = TRUE];

  //TMT.TMT(caseup, casehistorOwner, casehistorStat, idQueue, idUser, bh);
  //TMTRework.TMT(caseup, casehistorOwner, casehistorStat, idQueue, idUser, bh);
      if(System.isFuture() == false && System.isBatch() == false){ 
        TMTRework.TMT(idList);
    }
}
}