force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Retail</fullName>
            </value>
            <value>
                <fullName>Retail - Sinistres</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
            <value>
                <fullName>Gestion sinistre à la personne</fullName>
            </value>
            <value>
                <fullName>Manuel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_motif__c.field-meta.xml
<CustomField>
    <fullName>Sous_motif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acte de décès</fullName>
            </value>
            <value>
                <fullName>Ajout/suppression de prestation</fullName>
            </value>
            <value>
                <fullName>Ajout/Suppression prestation</fullName>
            </value>
            <value>
                <fullName>Ajout de prestation</fullName>
            </value>
            <value>
                <fullName>Alerte futur impayé</fullName>
            </value>
            <value>
                <fullName>Amende</fullName>
            </value>
            <value>
                <fullName>AND/AEN</fullName>
            </value>
            <value>
                <fullName>ANTS - Fin de Contrat</fullName>
            </value>
            <value>
                <fullName>ANTS - Fins de Contrat</fullName>
            </value>
            <value>
                <fullName>Appel pour l&apos;acceptation</fullName>
            </value>
            <value>
                <fullName>Appel pour le paiement</fullName>
            </value>
            <value>
                <fullName>Appel pour les RC</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>Assistance 1er loyer</fullName>
            </value>
            <value>
                <fullName>Assistance outils</fullName>
            </value>
            <value>
                <fullName>Assistance virement</fullName>
            </value>
            <value>
                <fullName>Assitance 1er loyer</fullName>
                <isActive>false</isActive>
                <label>Assitance 1er loyer</label>
            </value>
            <value>
                <fullName>Attestation de fin de contrat</fullName>
            </value>
            <value>
                <fullName>Attestation fin de contrat</fullName>
            </value>
            <value>
                <fullName>AUCUN</fullName>
                <isActive>false</isActive>
                <label>AUCUN</label>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
            <value>
                <fullName>Avenant de transfert</fullName>
            </value>
            <value>
                <fullName>Avis de citation à partie civile</fullName>
            </value>
            <value>
                <fullName>Avis de classement à victime</fullName>
            </value>
            <value>
                <fullName>Carte carburant</fullName>
            </value>
            <value>
                <fullName>Carte grise</fullName>
            </value>
            <value>
                <fullName>Carte grise - cession</fullName>
            </value>
            <value>
                <fullName>Carte grise - demande démarche</fullName>
            </value>
            <value>
                <fullName>Carte grise - en cours de contrat</fullName>
            </value>
            <value>
                <fullName>Demande info cession</fullName>
            </value>
            <value>
                <fullName>Gestion décès</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Requ_te_standard.recordType-meta.xml
<RecordType>
    <fullName>Requ_te_standard</fullName>
    <active>true</active>
    <businessProcess>FR_DefaultSupportProcess</businessProcess>
    <label>Requête standard</label>
</RecordType>

force-app/main/default/objects/KeywordDetectionRule__mdt/KeywordDetectionRule__mdt.object-meta.xml
<CustomObject>
    <label>KeywordDetectionRule</label>
    <pluralLabel>KeywordDetectionRules</pluralLabel>
</CustomObject>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Destinataires__c.field-meta.xml
<CustomField>
    <fullName>Destinataires__c</fullName>
    <label>Destinataires</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Expediteurs__c.field-meta.xml
<CustomField>
    <fullName>Expediteurs__c</fullName>
    <label>Expéditeurs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/File_d_attente__c.field-meta.xml
<CustomField>
    <fullName>File_d_attente__c</fullName>
    <label>File d&apos;attente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Operateur__c.field-meta.xml
<CustomField>
    <fullName>Operateur__c</fullName>
    <label>Opérateur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commence par</fullName>
                <default>true</default>
                <label>Commence par</label>
            </value>
            <value>
                <fullName>Contient</fullName>
            </value>
            <value>
                <fullName>Mot entier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Ou__c.field-meta.xml
<CustomField>
    <fullName>Ou__c</fullName>
    <label>Où ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objet</fullName>
                <default>true</default>
                <label>Objet</label>
            </value>
            <value>
                <fullName>Corps</fullName>
            </value>
            <value>
                <fullName>Objet/Corps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Priorite__c.field-meta.xml
<CustomField>
    <fullName>Priorite__c</fullName>
    <label>Priorité</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Sous_motif__c.field-meta.xml
<CustomField>
    <fullName>Sous_motif__c</fullName>
    <label>Sous-motif</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KeywordDetection_TEST.cls
@IsTest
public class KeywordDetection_TEST {
    
    @isTest static void testRechercheObjetValable(){
        //Setup
       //Recordtype impRecordTypeId=[select id,DeveloperName from recordtype where DeveloperName='Requ_te_standard' limit 1 ];
        Case cse = createTestCase();
        cse.Equipe__c='Recouvrement - Retail';
        cse.Motif__c='Amiable';
        cse.Sous_motif__c='Amende';
        update cse;
        EmailMessage email = createEmail(cse.Id,'Objet','Manuel');
        
        //Test
        Test.startTest();
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Recouvrement - Retail', caseToAssert.Equipe__c);
        System.assertEquals('Amiable', caseToAssert.Motif__c);
        System.assertEquals('Amende', caseToAssert.Sous_motif__c);
 
    }
        @isTest static void testRechercheObjetNonValable(){
        //Setup
        Recordtype impRecordTypeId=[select id,DeveloperName from recordtype where DeveloperName='Requ_te_standard' limit 1 ];
        Case cse = createTestCase();
        EmailMessage email = createEmail(cse.Id,'Objet','Tutu');
        
        //Test
        Test.startTest();
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Acceptation Annexes', caseToAssert.Equipe__c);
        System.assertEquals('Divers', caseToAssert.Motif__c);
        System.assertEquals(null, caseToAssert.Sous_motif__c);
 
    }
    @isTest static void testRechercheCorpsValable(){
        //Setup
        //Recordtype impRecordTypeId=[select id,DeveloperName from recordtype where DeveloperName='Requ_te_standard' limit 1 ];
        Case cse = createTestCase();
        cse.Equipe__c='Fleet - Fins de contrat';
        cse.Motif__c='Cession';
        cse.Sous_motif__c='Demande info cession';
        update cse;        
        EmailMessage email = createEmail(cse.Id,'Corps','Demande info cession');
        
        //Test
        Test.startTest();
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Fleet - Fins de contrat', caseToAssert.Equipe__c);
        System.assertEquals('Cession', caseToAssert.Motif__c);
        System.assertEquals('Demande info cession', caseToAssert.Sous_motif__c);
        
        
    }
    @isTest static void testRechercheCorpsNonValable(){
        //Setup
        Case cse = createTestCase();
        EmailMessage email = createEmail(cse.Id,'Corps','Tralala');
        
        //Test
        Test.startTest();
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Acceptation Annexes', caseToAssert.Equipe__c);
        System.assertEquals('Divers', caseToAssert.Motif__c);
        System.assertEquals(null, caseToAssert.Sous_motif__c);
 
    }
    @isTest static void testRechercheObjetCorpsValable(){
        //Setup
        Case cse = createTestCase();
        cse.Equipe__c='Retail - Sinistres';
        cse.Motif__c='Gestion sinistre à la personne';
        cse.Sous_motif__c='Gestion décès';
        update cse;  
        //Test
        Test.startTest();
        EmailMessage email = createEmail(cse.Id,'Objet/Corps','Gestion sinistre à la personne');
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Retail - Sinistres', caseToAssert.Equipe__c);
        System.assertEquals('Gestion sinistre à la personne', caseToAssert.Motif__c);
        System.assertEquals('Gestion décès', caseToAssert.Sous_motif__c);
        
        
    }
    @isTest static void testRechercheObjetCorpsNonValable(){
        //Setup
        Case cse = createTestCase();
        
        //Test
        Test.startTest();
        EmailMessage email = createEmail(cse.Id,'Objet/Corps','Rien à trouver');        
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Acceptation Annexes', caseToAssert.Equipe__c);
        System.assertEquals('Divers', caseToAssert.Motif__c);
        System.assertEquals(null, caseToAssert.Sous_motif__c);
        
        
    }       
    
       @isTest static void testmatchingThePattern(){
        //Setup
        KeywordDetectionRule__mdt rulesList= [SELECT Destinataires__c, Expediteurs__c, Expression__c, File_d_attente__c, Motif__c, Sous_motif__c, Ou__c, Priorite__c, Operateur__c FROM KeywordDetectionRule__mdt  limit 1];
        Group sc =[select Id from Group where  Type = 'Queue' limit 1];
        //queueMap=[select developpername,Id from Group where  Type = 'Queue' limit 1];
        Map<String,Id> queueMap= new Map<String,String>();
            
            for (Group theGroup:[Select Id, Name from Group where Type = 'Queue' limit 1])
            {
               queueMap.put(theGroup.Name,theGroup.Id);
            }
        
        
        Pattern keywordPattern = Pattern.compile('a*b');
        //Map<String,Id> queueMap= new Map<String,Id> ();
        Case cse = createTestCase();
        cse.Equipe__c='Retail - Sinistres';
        cse.Motif__c='Gestion sinistre à la personne';
        cse.Sous_motif__c='Gestion décès';
        cse.ownerid=sc.id;
        update cse;  
        //Test
        Test.startTest();
        
        System.assert(KeywordDetection.matchingThePattern(rulesList, keywordPattern,'aaaaab','000833',queueMap,cse));
        Test.stopTest();

        
    } 
    
       @isTest static void testconstructRegexFromOperator(){
        //Setup
       // First, instantiate a new Pattern object "MyPattern"
            Pattern MyPattern = Pattern.compile('a*b');
            Matcher MyMatcher = MyPattern.matcher('aaaaab');
           Boolean Test = Pattern.matches('a*b', 'aaaaab');
        
        //Test
       // Test.startTest();
        
         KeywordDetection.constructRegexFromOperator('Commence par',''); 
         KeywordDetection.constructRegexFromOperator('Contient',''); 
         KeywordDetection.constructRegexFromOperator('Mot entier','');     
        //Test.stopTest();
        
        
        
    }  
    
    @isTest static void testRechercheObjetCorpsDestinataire(){
        //Setup
        Case cse = createTestCase();
        
        //Test
        Test.startTest();
        EmailMessage email = createEmail(cse.Id,'Objet/Corps','Rien à trouver');        
        Test.stopTest();
        
        //Asserts
        Case caseToAssert = [SELECT ID,Equipe__c,motif__c,sous_Motif__c FROM Case WHERE ID =: cse.Id];
        System.assertEquals('Acceptation Annexes', caseToAssert.Equipe__c);
        System.assertEquals('Divers', caseToAssert.Motif__c);
        System.assertEquals(null, caseToAssert.Sous_motif__c);
        
        
    } 
    
    //Test utilitary methods
     public static Case createTestCase(){
     Recordtype impRecordTypeId=[select id,DeveloperName from recordtype where DeveloperName='Requ_te_standard' limit 1 ];
        Case cas = new Case(Origin ='Email', Status ='A traiter',RecordTypeId=impRecordTypeId.id, Equipe__c = 'Acceptation Annexes', Motif__c = 'Divers');
        insert cas;
        return cas;
    }

    public static EmailMessage createEmail(String cseId,String lieuOuChercher,String valeurExpression){
        EmailMessage email = new EmailMessage();
        email.ToAddress = 'rcfleet-uat@vwfs.com';
        email.incoming=true;
        switch on lieuOuChercher{
            when 'Objet'{
                email.Subject = 'Test Contrat ' + valeurExpression;
                email.TextBody = 'le corps du mail ';
            }
            when 'Corps'{
                email.Subject = 'Test Contrat ';
                email.TextBody = 'le corps du mail et le mot ' + valeurExpression;
            }
            when 'Objet/Corps'{
                email.Subject = 'Test Contrat ' + valeurExpression;
                email.TextBody = 'le corps du mail et le mot ' + valeurExpression;
            }
        }
        email.ParentId = cseId;
        insert email;
        return email;
      }
}