force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_motif__c.field-meta.xml
<CustomField>
    <fullName>Sous_motif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acte de décès</fullName>
            </value>
            <value>
                <fullName>Ajout/suppression de prestation</fullName>
            </value>
            <value>
                <fullName>Ajout/Suppression prestation</fullName>
            </value>
            <value>
                <fullName>Ajout de prestation</fullName>
            </value>
            <value>
                <fullName>Alerte futur impayé</fullName>
            </value>
            <value>
                <fullName>Amende</fullName>
            </value>
            <value>
                <fullName>AND/AEN</fullName>
            </value>
            <value>
                <fullName>ANTS - Fin de Contrat</fullName>
            </value>
            <value>
                <fullName>ANTS - Fins de Contrat</fullName>
            </value>
            <value>
                <fullName>Appel pour l&apos;acceptation</fullName>
            </value>
            <value>
                <fullName>Appel pour le paiement</fullName>
            </value>
            <value>
                <fullName>Appel pour les RC</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>Assistance 1er loyer</fullName>
            </value>
            <value>
                <fullName>Assistance outils</fullName>
            </value>
            <value>
                <fullName>Assistance virement</fullName>
            </value>
            <value>
                <fullName>Assitance 1er loyer</fullName>
                <isActive>false</isActive>
                <label>Assitance 1er loyer</label>
            </value>
            <value>
                <fullName>Attestation de fin de contrat</fullName>
            </value>
            <value>
                <fullName>Attestation fin de contrat</fullName>
            </value>
            <value>
                <fullName>AUCUN</fullName>
                <isActive>false</isActive>
                <label>AUCUN</label>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
            <value>
                <fullName>Avenant de transfert</fullName>
            </value>
            <value>
                <fullName>Avis de citation à partie civile</fullName>
            </value>
            <value>
                <fullName>Avis de classement à victime</fullName>
            </value>
            <value>
                <fullName>Carte carburant</fullName>
            </value>
            <value>
                <fullName>Carte grise</fullName>
            </value>
            <value>
                <fullName>Carte grise - cession</fullName>
            </value>
            <value>
                <fullName>Carte grise - demande démarche</fullName>
            </value>
            <value>
                <fullName>Carte grise - en cours de contrat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/KeywordDetectionRule__mdt.object-meta.xml
<CustomObject>
    <label>KeywordDetectionRule</label>
    <pluralLabel>KeywordDetectionRules</pluralLabel>
</CustomObject>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Destinataires__c.field-meta.xml
<CustomField>
    <fullName>Destinataires__c</fullName>
    <label>Destinataires</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Expediteurs__c.field-meta.xml
<CustomField>
    <fullName>Expediteurs__c</fullName>
    <label>Expéditeurs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/File_d_attente__c.field-meta.xml
<CustomField>
    <fullName>File_d_attente__c</fullName>
    <label>File d&apos;attente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Operateur__c.field-meta.xml
<CustomField>
    <fullName>Operateur__c</fullName>
    <label>Opérateur</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commence par</fullName>
                <default>true</default>
                <label>Commence par</label>
            </value>
            <value>
                <fullName>Contient</fullName>
            </value>
            <value>
                <fullName>Mot entier</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Ou__c.field-meta.xml
<CustomField>
    <fullName>Ou__c</fullName>
    <label>Où ?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Objet</fullName>
                <default>true</default>
                <label>Objet</label>
            </value>
            <value>
                <fullName>Corps</fullName>
            </value>
            <value>
                <fullName>Objet/Corps</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Priorite__c.field-meta.xml
<CustomField>
    <fullName>Priorite__c</fullName>
    <label>Priorité</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/KeywordDetectionRule__mdt/fields/Sous_motif__c.field-meta.xml
<CustomField>
    <fullName>Sous_motif__c</fullName>
    <label>Sous-motif</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/KeywordDetection.cls
public class KeywordDetection {
  public static Case rulesMatcher(EmailMessage emailEntrant, Case parentCase) {
    //////////////////////////// Déclarations ////////////////////////////
    //Case parentCase = new Case(/* Id = emailEntrant.ParentId */);
    List<KeywordDetectionRule__mdt> rulesList;
    List<Group> queueList = new List<Group>();
    Map<String, Id> queueMap = new Map<String, Id>();
    Boolean isMatched = false;
    String regex;

    ////////////////////////////// Queries ///////////////////////////////
    //Query pour avoir la liste des rules concernées
    rulesList = [
      SELECT
        Destinataires__c,
        Expediteurs__c,
        Expression__c,
        File_d_attente__c,
        Motif__c,
        Sous_motif__c,
        Ou__c,
        Priorite__c,
        Operateur__c
      FROM KeywordDetectionRule__mdt
      WHERE Destinataires__c = :emailEntrant.ToAddress
      ORDER BY Priorite__c DESC
    ];
    System.debug('emailToAdress = ' + emailEntrant.ToAddress);
    System.debug('ruleslist = ' + rulesList);
    //Query pour avoir la liste des queues
    queueList = [SELECT Id, Name FROM Group WHERE Type = 'Queue'];

    //Formation d'une Map <Nom de la queue,Id de la queue>
    for (Group q : queueList) {
      queueMap.put(q.Name, q.Id);
    }

    //Suppression des accents dans le mail entrant
    if (emailEntrant.Subject != null) {
      emailEntrant.Subject = clean(emailEntrant.Subject);
    }
    if (emailEntrant.TextBody != null) {
      emailEntrant.TextBody = clean(emailEntrant.TextBody);
    }

    ////////////////////// Détection des mots clés ///////////////////////
    for (KeywordDetectionRule__mdt ruleChecking : rulesList) {
      //Suppression des accents dans la regle
      ruleChecking.Expression__c = clean(ruleChecking.Expression__c);

      ///On construit le regex en fonction de l'opérateur indiqué dans la règle
      regex = constructRegexFromOperator(
        ruleChecking.Operateur__c,
        ruleChecking.Expression__c
      );

      Pattern keywordPattern = Pattern.compile(regex);

      if (
        ruleChecking.Ou__c == 'Objet' && String.IsNotBlank(emailEntrant.Subject)
      ) {
        isMatched = matchingThePattern(
          ruleChecking,
          keywordPattern,
          emailEntrant.Subject,
          emailEntrant.ParentId,
          queueMap,
          parentCase
        );
        if (isMatched) {
          break;
        }
      } else if (
        ruleChecking.Ou__c == 'Corps' &&
        String.IsNotBlank(emailEntrant.TextBody)
      ) {
        isMatched = matchingThePattern(
          ruleChecking,
          keywordPattern,
          emailEntrant.TextBody,
          emailEntrant.ParentId,
          queueMap,
          parentCase
        );
        if (isMatched) {
          break;
        }
      } else if (
        ruleChecking.Ou__c == 'Objet/Corps' &&
        (String.IsNotBlank(emailEntrant.Subject) ||
        String.IsNotBlank(emailEntrant.TextBody))
      ) {
        String objetCorps = emailEntrant.Subject + ' ' + emailEntrant.TextBody;
        isMatched = matchingThePattern(
          ruleChecking,
          keywordPattern,
          objetCorps,
          emailEntrant.ParentId,
          queueMap,
          parentCase
        );
        if (isMatched) {
          break;
        }
      }
    }

    return parentCase;
  }

  public static Boolean matchingThePattern(
    KeywordDetectionRule__mdt rule,
    Pattern keywordPattern,
    String lieuOuChercher,
    String parentId,
    Map<String, Id> queueMap,
    Case parentCase
  ) {
    System.debug('lieuOuChercher = ' + lieuOuChercher);
    Boolean isMatched = false;
    Matcher keywordMatcher = keywordPattern.matcher(lieuOuChercher);
    System.debug('Motif = ' + rule.Motif__c);
    System.debug('Sous-Motif = ' + rule.Sous_motif__c);
    System.debug('File d\'attente = ' + rule.File_d_attente__c);
    System.debug('OwnerId = ' + queueMap.get(rule.File_d_attente__c));
    if (keywordMatcher.find()) {
      //Case creation
      System.debug('je suis dans le if');
      parentCase.Motif__c = rule.Motif__c;
      parentCase.Sous_motif__c = rule.Sous_motif__c;
      parentCase.Equipe__c = rule.File_d_attente__c;
      parentCase.OwnerId = queueMap.get(rule.File_d_attente__c);
      isMatched = true;
    }
    return isMatched;
  }

  /////Méthode qui reçoit un String et enlève tous les accents//////
  private static String clean(String stringToClean) {
    String acc = 'ÀÂÄÇÉÈÊËÎÏÛÜÔÖàâäçéèêëîïôöùûü';
    String maj = 'AAACEEEEIIUUOOaaaceeeeiioouuu';

    String cleanString = '';
    for (Integer i = 0; i < stringToClean.length(); i++) {
      String car = stringToClean.substring(i, i + 1);
      Integer idx = acc.indexOf(car);
      if (idx != -1) {
        cleanString += maj.substring(idx, idx + 1);
      } else {
        cleanString += car;
      }
    }

    return cleanString;
  }

  public static String constructRegexFromOperator(
    String Operateur,
    String Expression
  ) {
    String boundaryCommencePar = '(?m)(?u)(?i)\\b',
      boundaryContient = '(?m)(?u)(?i)',
      boundaryMotEntierFin = '\\b',
      regex;
    if (Operateur == 'Commence par' || Operateur == null || Operateur == '') {
      regex = boundaryCommencePar + Expression;
    } else if (Operateur == 'Contient') {
      regex = boundaryContient + Expression;
    } else if (Operateur == 'Mot entier') {
      regex = boundaryCommencePar + Expression + boundaryMotEntierFin;
    }
    return regex;
  }
}