force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sous_motif__c.field-meta.xml
<CustomField>
    <fullName>Sous_motif__c</fullName>
    <label>Sous-motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motif__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acte de décès</fullName>
            </value>
            <value>
                <fullName>Ajout/suppression de prestation</fullName>
            </value>
            <value>
                <fullName>Ajout/Suppression prestation</fullName>
            </value>
            <value>
                <fullName>Ajout de prestation</fullName>
            </value>
            <value>
                <fullName>Alerte futur impayé</fullName>
            </value>
            <value>
                <fullName>Amende</fullName>
            </value>
            <value>
                <fullName>AND/AEN</fullName>
            </value>
            <value>
                <fullName>ANTS - Fin de Contrat</fullName>
            </value>
            <value>
                <fullName>ANTS - Fins de Contrat</fullName>
            </value>
            <value>
                <fullName>Appel pour l&apos;acceptation</fullName>
            </value>
            <value>
                <fullName>Appel pour le paiement</fullName>
            </value>
            <value>
                <fullName>Appel pour les RC</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>Assistance 1er loyer</fullName>
            </value>
            <value>
                <fullName>Assistance outils</fullName>
            </value>
            <value>
                <fullName>Assistance virement</fullName>
            </value>
            <value>
                <fullName>Assitance 1er loyer</fullName>
                <isActive>false</isActive>
                <label>Assitance 1er loyer</label>
            </value>
            <value>
                <fullName>Attestation de fin de contrat</fullName>
            </value>
            <value>
                <fullName>Attestation fin de contrat</fullName>
            </value>
            <value>
                <fullName>AUCUN</fullName>
                <isActive>false</isActive>
                <label>AUCUN</label>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Autres</fullName>
            </value>
            <value>
                <fullName>Avenant de transfert</fullName>
            </value>
            <value>
                <fullName>Avis de citation à partie civile</fullName>
            </value>
            <value>
                <fullName>Avis de classement à victime</fullName>
            </value>
            <value>
                <fullName>Carte carburant</fullName>
            </value>
            <value>
                <fullName>Carte grise</fullName>
            </value>
            <value>
                <fullName>Carte grise - cession</fullName>
            </value>
            <value>
                <fullName>Carte grise - demande démarche</fullName>
            </value>
            <value>
                <fullName>Carte grise - en cours de contrat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchCaseTMT_TEST.cls
@IsTest
public class BatchCaseTMT_TEST {
    @isTest
    static void BatchCaseTMT_TEST() {
        Case ca = new Case();
        ca.Subject = 'ctr Test';
        ca.Status = 'A traiter';
        ca.Priority = 'Low';
        ca.Origin = 'Email';
        ca.Equipe__c = 'Recouvrement - Retail';
        ca.Motif__c = 'Amiable';
        ca.Sous_motif__c = 'Amende';
        insert ca;

        Test.startTest();
        BatchCaseTMT obj = new BatchCaseTMT();
        DataBase.executeBatch(obj);
        Test.stopTest();
    }
}