force-app/main/default/objects/Account/recordTypes/ClientB2B.recordType-meta.xml
<RecordType>
    <fullName>ClientB2B</fullName>
    <active>true</active>
    <description>Pour les comptes clients B2B</description>
    <label>Client B2B</label>
</RecordType>

force-app/main/default/objects/Case/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <formula>Contrat__r.Code_statut_contrat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code statut contrat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_d_ch_ance__c.field-meta.xml
<CustomField>
    <fullName>Date_d_ch_ance__c</fullName>
    <label>Date d&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_l_alerte__c.field-meta.xml
<CustomField>
    <fullName>Date_de_l_alerte__c</fullName>
    <formula>Contrat__r.Date_de_l_alerte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de l&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Produit_financier__c.field-meta.xml
<CustomField>
    <fullName>Produit_financier__c</fullName>
    <formula>TEXT(Contrat__r.Produit_financier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produit financier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Gestion_d_impay.recordType-meta.xml
<RecordType>
    <fullName>Gestion_d_impay</fullName>
    <active>true</active>
    <businessProcess>FR_DefaultSupportProcess</businessProcess>
    <label>Gestion d’impayé</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact_Client.recordType-meta.xml
<RecordType>
    <fullName>Contact_Client</fullName>
    <active>true</active>
    <label>Contact Client</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <description>Code du statut du contrat</description>
    <label>Code statut contrat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Compte_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Compte_client_associe__c</fullName>
    <label>Compte client associé</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats Client</relationshipLabel>
    <relationshipName>ContratsClient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contact_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Contact_client_associe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact client associé</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact client associé)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Date_de_l_alerte__c.field-meta.xml
<CustomField>
    <fullName>Date_de_l_alerte__c</fullName>
    <description>Date de l&apos;alerte</description>
    <label>Date de l&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Numero_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_contrat__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de contrat</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Produit_financier__c.field-meta.xml
<CustomField>
    <fullName>Produit_financier__c</fullName>
    <label>Produit financier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crédit</fullName>
            </value>
            <value>
                <fullName>Crédit Bail</fullName>
            </value>
            <value>
                <fullName>LLD</fullName>
            </value>
            <value>
                <fullName>LOA</fullName>
            </value>
            <value>
                <fullName>CRE</fullName>
            </value>
            <value>
                <fullName>CRV</fullName>
            </value>
            <value>
                <fullName>ASV</fullName>
            </value>
            <value>
                <fullName>CRB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchContratCaseCampaignCreate_TEST.cls
@IsTest
public class BatchContratCaseCampaignCreate_TEST {
  @isTest
  static void TestBatch() {
    Recordtype rtaccid = [
      SELECT id, DeveloperName
      FROM recordtype
      WHERE DeveloperName = 'ClientB2B'
      LIMIT 1
    ];
    Recordtype rtcontid = [
      SELECT id, DeveloperName
      FROM recordtype
      WHERE DeveloperName = 'Contact_Client'
      LIMIT 1
    ];
    Recordtype impRecordTypeId = [
      SELECT id, DeveloperName
      FROM recordtype
      WHERE DeveloperName = 'Gestion_d_impay'
      LIMIT 1
    ];
    //créer le compte B2B
    Account accnt = new Account();
    accnt.Name = 'TestBatche';
    accnt.RecordTypeId = rtaccid.id;
    insert accnt;

    //créer le contact
    Contact cont = new Contact();
    cont.FirstName = 'Contact';
    cont.LastName = 'batch';
    cont.RecordTypeId = rtcontid.id;
    cont.AccountId = accnt.id;
    insert cont;

    //créer le contrat
    List<Contract__c> insertcontrat = new List<Contract__c>();
    Contract__c ctrt = new Contract__c();
    ctrt.Name = '12341234LLD';
    ctrt.Code_statut_contrat__c = 'RECAMI';
    ctrt.Compte_client_associe__c = accnt.ID;
    ctrt.Contact_client_associe__c = cont.Id;
    ctrt.Produit_financier__c = 'LLD';
    ctrt.Numero_de_contrat__c = '12341234LLD';
    ctrt.Date_de_l_alerte__c = date.today();//date.parse('07/04/2022');
    insertcontrat.add(ctrt);

    Contract__c ctrt2 = new Contract__c();
    ctrt2.Name = '123411134LOA';
    ctrt2.Code_statut_contrat__c = 'TPCX';
    ctrt2.Compte_client_associe__c = accnt.ID;
    ctrt2.Contact_client_associe__c = cont.Id;
    ctrt2.Produit_financier__c = 'LOA';
    ctrt2.Numero_de_contrat__c = '123411134LOA';
    insertcontrat.add(ctrt2);

    Contract__c ctrt3 = new Contract__c();
    ctrt3.Name = '12341224LLD';
    ctrt3.Code_statut_contrat__c = 'RCONO';
    ctrt3.Compte_client_associe__c = accnt.ID;
    ctrt3.Contact_client_associe__c = cont.Id;
    ctrt3.Produit_financier__c = 'LLD';
    ctrt3.Numero_de_contrat__c = '12341224LLD';
    insertcontrat.add(ctrt3);

    Contract__c ctrt4 = new Contract__c();
    ctrt4.Name = '12341224CRE';
    ctrt4.Code_statut_contrat__c = 'BDFREC';
    ctrt4.Compte_client_associe__c = accnt.ID;
    ctrt4.Contact_client_associe__c = cont.Id;
    ctrt4.Produit_financier__c = 'CRE';
    ctrt4.Numero_de_contrat__c = '12341224CRE';
    ctrt4.Date_de_l_alerte__c = date.parse('12/04/2022');
    insertcontrat.add(ctrt4);

    Contract__c ctrt5 = new Contract__c();
    ctrt5.Name = '12341224CRB';
    ctrt5.Code_statut_contrat__c = 'RLJ';
    ctrt5.Compte_client_associe__c = accnt.ID;
    ctrt5.Contact_client_associe__c = cont.Id;
    ctrt5.Produit_financier__c = 'CRB';
    ctrt5.Numero_de_contrat__c = '12341224CRB';
    ctrt5.Date_de_l_alerte__c = date.parse('10/04/2022');
    insertcontrat.add(ctrt5);

    Contract__c ctrt6 = new Contract__c();
    ctrt6.Name = '12348924CRB';
    ctrt6.Code_statut_contrat__c = 'RLJ';
    ctrt6.Compte_client_associe__c = accnt.ID;
    ctrt6.Contact_client_associe__c = cont.Id;
    ctrt6.Produit_financier__c = 'CRB';
    ctrt6.Numero_de_contrat__c = '12348924CRB';
    ctrt6.Date_de_l_alerte__c = date.parse('10/04/2022');
    insertcontrat.add(ctrt6);
    insert insertcontrat;

    //créer le case
    List<Case> insertcase = new List<Case>();
    Case ca = new Case();
    Case ca2 = new Case();
    Case ca3 = new Case();
    Case ca4 = new Case();
    Database.DMLOptions dmo = new Database.DMLOptions();
    dmo.assignmentRuleHeader.useDefaultRule = true;
    ca.setOptions(dmo);
    ca.Subject = 'ctr Test';
    ca.RecordTypeId = impRecordTypeId.id;
    ca.Date_d_ch_ance__c = date.parse('10/04/2022');
    ca.Status = 'A traiter';
    ca.Contrat__c = ctrt.id;
    ca.AccountId = ctrt.Contact_client_associe__r.AccountId;
    ca.ContactId = ctrt.Contact_client_associe__c;
    ca.Priority = 'Low';
    ca.Origin = 'Gestion_d_impaye';
    ca.Equipe__c = 'Acceptation Annexes';
    ca.Motif__c = 'Divers';
    insertcase.add(ca);

    ca2.setOptions(dmo);
    ca2.Subject = 'ctr Test';
    ca2.RecordTypeId = impRecordTypeId.id;
    ca2.Date_d_ch_ance__c = date.parse('11/04/2022');
    ca2.Status = 'A traiter';
    ca2.Contrat__c = ctrt4.id;
    ca2.AccountId = ctrt4.Contact_client_associe__r.AccountId;
    ca2.ContactId = ctrt4.Contact_client_associe__c;
    ca2.Priority = 'Low';
    ca2.Origin = 'Gestion_d_impaye';
    ca2.Equipe__c = 'Acceptation Annexes';
    ca2.Motif__c = 'Divers';
    insertcase.add(ca2);

    ca4.setOptions(dmo);
    ca4.Subject = 'ctr Test';
    ca4.RecordTypeId = impRecordTypeId.id;
    ca4.Date_d_ch_ance__c = date.parse('10/04/2022');
    ca4.Status = 'Requête déjà traitée (doublon)';
    ca4.Equipe__c = 'Acceptation Annexes';
    ca4.Motif__c = 'Divers';
    ca4.Contrat__c = ctrt5.id;
    ca4.AccountId = ctrt5.Contact_client_associe__r.AccountId;
    ca4.ContactId = ctrt5.Contact_client_associe__c;
    ca4.Priority = 'Low';
    ca4.Origin = 'Gestion_d_impaye';
    insertcase.add(ca4);

    ca3.setOptions(dmo);
    ca3.Subject = 'ctr Test';
    ca3.RecordTypeId = impRecordTypeId.id;
    ca3.Date_d_ch_ance__c = date.parse('09/04/2022');
    ca3.Status = 'A traiter';
    ca3.Contrat__c = ctrt5.id;
    ca3.AccountId = ctrt5.Contact_client_associe__r.AccountId;
    ca3.ContactId = ctrt5.Contact_client_associe__c;
    ca3.Priority = 'Low';
    ca3.Origin = 'Gestion_d_impaye';
    ca3.Equipe__c = 'Acceptation Annexes';
    ca3.Motif__c = 'Divers';
    insertcase.add(ca3);

    insert insertcase;

    Test.startTest();
    BatchContratCaseCampaignCreate obj = new BatchContratCaseCampaignCreate();
    DataBase.executeBatch(obj);
    Test.stopTest();
  }
}