force-app/main/default/objects/Account/recordTypes/ClientB2B.recordType-meta.xml
<RecordType>
    <fullName>ClientB2B</fullName>
    <active>true</active>
    <description>Pour les comptes clients B2B</description>
    <label>Client B2B</label>
</RecordType>

force-app/main/default/objects/Case/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact_Client.recordType-meta.xml
<RecordType>
    <fullName>Contact_Client</fullName>
    <active>true</active>
    <label>Contact Client</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Compte_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Compte_client_associe__c</fullName>
    <label>Compte client associé</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats Client</relationshipLabel>
    <relationshipName>ContratsClient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contact_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Contact_client_associe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact client associé</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact client associé)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Numero_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_contrat__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de contrat</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - RC</fullName>
            </value>
            <value>
                <fullName>Paiement Fleet</fullName>
            </value>
            <value>
                <fullName>Paiement Grands comptes</fullName>
            </value>
            <value>
                <fullName>Paiement Manuel</fullName>
            </value>
            <value>
                <fullName>Paiement régularisation</fullName>
            </value>
            <value>
                <fullName>Paiement Retail</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB divers</fullName>
            </value>
            <value>
                <fullName>Qualité DORAB réclamations</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Administratif et Banque de France</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Affaires Spéciales</fullName>
            </value>
            <value>
                <fullName>Recouvrement - Fleet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EmailMessageTriggerHandler_TEST.cls
@IsTest
public class EmailMessageTriggerHandler_TEST {
    @isTest
    static void testHandleTrigger() {
        List<EmailMessage> emailList = new List<EmailMessage>();
        EmailMessage email;
        emailList.add(email);
        
        System.TriggerOperation AFTER_INSERT;
        System.TriggerOperation BEFORE_INSERT;
        
        EmailMessageTriggerHandler.handleTrigger(emailList, AFTER_INSERT);
        EmailMessageTriggerHandler.handleTrigger(emailList, BEFORE_INSERT);
    }
    @isTest
    public static void TestInsertEmailMessage() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        User u = [SELECT Id,Equipe__c,UserRoleId,IsActive,UserRole.DeveloperName  FROM User WHERE ProfileId =: p.Id AND IsActive=True AND (UserRole.DeveloperName!='agent_RC_ext' OR UserRole.DeveloperName!='superviseur_RC_ext') LIMIT 1];
        Group grp1 = new Group();
        grp1.Name = 'newGroupe';
        Insert grp1;
        
        System.runAs(u) {
            Recordtype rtaccid = [
                SELECT id, DeveloperName
                FROM recordtype
                WHERE DeveloperName = 'ClientB2B'
                LIMIT 1
            ];
            Recordtype rtcontid = [
                SELECT id, DeveloperName
                FROM recordtype
                WHERE DeveloperName = 'Contact_Client'
                LIMIT 1
            ];
            
            //créer le compte B2B
            Account acc1 = new Account();
            acc1.Name = 'Testemail';
            acc1.RecordTypeId = rtaccid.id;
            insert acc1;
            
            //créer le contact
            Contact con1 = new Contact();
            con1.FirstName = 'mOMaer';
            con1.LastName = 'tesa';
            con1.RecordTypeId = rtcontid.id;
            con1.AccountId = acc1.id;
            insert con1;
            
            //créer le contrat
            Contract__c ctra1 = new Contract__c();
            ctra1.Name = '98989098LOA';
            ctra1.Numero_de_contrat__c = '98989098LOA';
            ctra1.Compte_client_associe__c = acc1.Id;
            ctra1.Contact_client_associe__c = con1.Id;
            insert ctra1;
            
            //créer le case
            
            Case c = new Case();
            c.Subject = '98989098LOA';
            c.Status = 'A traiter';
            c.Contrat__c = ctra1.id;
            c.ContactId = ctra1.Contact_client_associe__c;
            c.AccountId = ctra1.Contact_client_associe__r.AccountId;
            c.Priority = 'Low';
            c.Origin = 'Email';
            c.Equipe__c = 'Fleet - Fins de contrat';
            c.Motif__c = 'Retail';
            insert c;

            //Insert emailmessage for case
            EmailMessage[] em = new List<EmailMessage>();
            EmailMessage email = new EmailMessage();
            email.FromAddress = 'test@abc.org';
            email.Incoming = true;
            email.ToAddress = 'test@xyz.org';
            email.TextBody = '98989098LOA ' + '[ref:' + c.Id + ']';
            email.Subject = '98989098LOA';
            email.ParentId = c.Id;
            
            em.add(email);
            
            insert em;

            //créer le case
            Case c1 = new Case();
            c1.Subject = '98989099LOA';
            c1.Status = 'Résolue';
            c1.Contrat__c = ctra1.id;
            c1.ContactId = ctra1.Contact_client_associe__c;
            c1.AccountId = ctra1.Contact_client_associe__r.AccountId;
            c1.Priority = 'Low';
            c1.Origin = 'Email';
            c1.Equipe__c = 'Fleet - Fins de contrat';
            c1.Motif__c = 'Retail';
            insert c1;
            
            //Insert emailmessage for case
            EmailMessage email1 = new EmailMessage();
            email1.FromAddress = 'test@abc.org';
            email1.Incoming = true;
            email1.ToAddress = 'test@xyz.org';
            email1.TextBody = '98989098LOA';
            email1.Subject = '98989098LOA';
            email1.ParentId = c1.Id;
            try{
                Insert email1;
            }catch(exception e){
                system.debug('e:'+e);
            }
            
            
            //Assert if case subject updated with emailmessage textbody value
            System.assertEquals(
                [SELECT Id, Subject FROM Case WHERE Id = :c.Id][0]
                .Subject,
                '98989098LOA'
            );
        }
    }
    
    @isTest
    static void TestInsertEmailMessage2() {
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator' LIMIT 1];
        UserRole role = [select Id,Name, DeveloperName from UserRole where DeveloperName='agent_RC_ext' LIMIT 1];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles',
        UserRoleId=role.Id,
        Equipe__c = 'Fleet - Fins de contrat',
        UserName='Testingojhvwfs@yopmail.com');
		Insert u;
        group grp1 = new group();
        grp1.Name = 'Fleet - Fins de contrat';    
        Insert grp1;
        system.debug('grp1:'+grp1);
        Group myQueue = [SELECT id,Related.Name,Name from Group where name='Fleet - Fins de contrat' limit 1];
        system.debug('myQueue:'+myQueue);
        System.runAs(u) {
            Recordtype rtaccid = [
                SELECT id, DeveloperName
                FROM recordtype
                WHERE DeveloperName = 'ClientB2B'
                LIMIT 1
            ];
            Recordtype rtcontid = [
                SELECT id, DeveloperName
                FROM recordtype
                WHERE DeveloperName = 'Contact_Client'
                LIMIT 1
            ];
            
            //créer le compte B2B
            Account acc1 = new Account();
            acc1.Name = 'Testemail';
            acc1.RecordTypeId = rtaccid.id;
            insert acc1;
            
            //créer le contact
            Contact con1 = new Contact();
            con1.FirstName = 'mOMaer';
            con1.LastName = 'tesa';
            con1.RecordTypeId = rtcontid.id;
            con1.AccountId = acc1.id;
            insert con1;
            
            //créer le contrat
            Contract__c ctra1 = new Contract__c();
            ctra1.Name = '98989098LOA';
            ctra1.Numero_de_contrat__c = '98989098LOA';
            ctra1.Compte_client_associe__c = acc1.Id;
            ctra1.Contact_client_associe__c = con1.Id;
            insert ctra1;
            
            //créer le case
            
            Case c = new Case();
            c.Subject = '98989098LOA';
            c.Status = 'A traiter';
            c.Contrat__c = ctra1.id;
            c.ContactId = ctra1.Contact_client_associe__c;
            c.AccountId = ctra1.Contact_client_associe__r.AccountId;
            c.Priority = 'Low';
            c.Origin = 'Email';
            c.Equipe__c = 'Fleet - Fins de contrat';
            c.Motif__c = 'Retail';
            c.OwnerId = myQueue.Id;
            insert c;
			
            //update c;
            //Insert emailmessage for case
            EmailMessage[] em = new List<EmailMessage>();
            EmailMessage email = new EmailMessage();
            email.FromAddress = 'test@abc.org';
            email.Incoming = true;
            email.ToAddress = 'test@xyz.org';
            email.TextBody = '98989098LOA';
            email.Subject = '98989098LOA';
            email.ParentId = c.Id;
            
            em.add(email);
            
            insert em;
            //créer le case
            Case c1 = new Case();
            c1.Subject = '98989099LOA';
            c1.Status = 'Résolue';
            c1.Contrat__c = ctra1.id;
            c1.ContactId = ctra1.Contact_client_associe__c;
            c1.AccountId = ctra1.Contact_client_associe__r.AccountId;
            c1.Priority = 'Low';
            c1.Origin = 'Email';
            c1.Equipe__c = 'Fleet - Fins de contrat';
            c1.Motif__c = 'Retail';
            insert c1;
            
            //Insert emailmessage for case
            EmailMessage email1 = new EmailMessage();
            email1.FromAddress = 'test@abc.org';
            email1.Incoming = true;
            email1.ToAddress = 'test@xyz.org';
            email1.TextBody = '98989098LOA';
            email1.Subject = '98989098LOA';
            email1.ParentId = c1.Id;
            try{
                Insert email1;
            }catch(exception e){
                system.debug('e:'+e);
            }
            
            
            //Assert if case subject updated with emailmessage textbody value
            System.assertEquals(
                [SELECT Id, Subject FROM Case WHERE Id = :c.Id][0]
                .Subject,
                '98989098LOA'
            );
        }
    }
}