force-app/main/default/objects/Account/recordTypes/ClientB2B.recordType-meta.xml
<RecordType>
    <fullName>ClientB2B</fullName>
    <active>true</active>
    <description>Pour les comptes clients B2B</description>
    <label>Client B2B</label>
</RecordType>

force-app/main/default/objects/Case/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <formula>Contrat__r.Code_statut_contrat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Code statut contrat</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contrat__c.field-meta.xml
<CustomField>
    <fullName>Contrat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrat</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Requêtes</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_d_ch_ance__c.field-meta.xml
<CustomField>
    <fullName>Date_d_ch_ance__c</fullName>
    <label>Date d&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Date_de_l_alerte__c.field-meta.xml
<CustomField>
    <fullName>Date_de_l_alerte__c</fullName>
    <formula>Contrat__r.Date_de_l_alerte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date de l&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Equipe__c.field-meta.xml
<CustomField>
    <fullName>Equipe__c</fullName>
    <label>Equipe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Acceptation Annexes</fullName>
            </value>
            <value>
                <fullName>ACCEPTATION B2C</fullName>
                <isActive>false</isActive>
                <label>ACCEPTATION B2C</label>
            </value>
            <value>
                <fullName>Acceptation Fleet Cellule Support</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet Transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Fleet VO</fullName>
            </value>
            <value>
                <fullName>Acceptation Refinancement/transfert</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail Vente en ligne</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VN</fullName>
            </value>
            <value>
                <fullName>Acceptation Retail VO</fullName>
            </value>
            <value>
                <fullName>Acceptation VGRF</fullName>
            </value>
            <value>
                <fullName>Acceptation VIP</fullName>
            </value>
            <value>
                <fullName>Acceptation VRGF</fullName>
                <isActive>false</isActive>
                <label>Acceptation VRGF</label>
            </value>
            <value>
                <fullName>CRC FLEET</fullName>
                <isActive>false</isActive>
                <label>CRC FLEET</label>
            </value>
            <value>
                <fullName>CRC retail</fullName>
                <isActive>false</isActive>
                <label>CRC retail</label>
            </value>
            <value>
                <fullName>Credit RESEAU</fullName>
                <isActive>false</isActive>
                <label>Credit RESEAU</label>
            </value>
            <value>
                <fullName>Crédit réseau 4 fois sans frais</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VN</fullName>
            </value>
            <value>
                <fullName>Crédit réseau affacturage VO</fullName>
            </value>
            <value>
                <fullName>Crédit réseau annexe 1</fullName>
            </value>
            <value>
                <fullName>Crédit réseau compliance</fullName>
            </value>
            <value>
                <fullName>Crédit réseau comptabilité</fullName>
            </value>
            <value>
                <fullName>Crédit réseau double financement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau Lamborghini</fullName>
            </value>
            <value>
                <fullName>Crédit réseau post traitement</fullName>
            </value>
            <value>
                <fullName>Crédit réseau PRA</fullName>
            </value>
            <value>
                <fullName>Crédit réseau RAC</fullName>
            </value>
            <value>
                <fullName>Fleet - Fins de contrat</fullName>
            </value>
            <value>
                <fullName>Fleet - Grands comptes</fullName>
            </value>
            <value>
                <fullName>Fleet - Partenaires</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Motif__c.field-meta.xml
<CustomField>
    <fullName>Motif__c</fullName>
    <label>Motif</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Equipe__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administratif</fullName>
            </value>
            <value>
                <fullName>Administratif RECVT</fullName>
            </value>
            <value>
                <fullName>Affacturage VN</fullName>
            </value>
            <value>
                <fullName>Affacturage VO</fullName>
            </value>
            <value>
                <fullName>Affaires spéciales</fullName>
            </value>
            <value>
                <fullName>Amiable</fullName>
            </value>
            <value>
                <fullName>Assistance</fullName>
            </value>
            <value>
                <fullName>Assistance outil</fullName>
            </value>
            <value>
                <fullName>Attestations contrat</fullName>
            </value>
            <value>
                <fullName>Autre</fullName>
            </value>
            <value>
                <fullName>Banque de France</fullName>
            </value>
            <value>
                <fullName>Cession</fullName>
            </value>
            <value>
                <fullName>Changement sur client</fullName>
            </value>
            <value>
                <fullName>Changement sur dossier</fullName>
            </value>
            <value>
                <fullName>Commandes</fullName>
            </value>
            <value>
                <fullName>Compta/Règlements</fullName>
            </value>
            <value>
                <fullName>Contactez-nous</fullName>
            </value>
            <value>
                <fullName>Contentieux</fullName>
            </value>
            <value>
                <fullName>Contraventions</fullName>
            </value>
            <value>
                <fullName>Contre-proposition</fullName>
            </value>
            <value>
                <fullName>Délai de traitement</fullName>
            </value>
            <value>
                <fullName>Délai de traitement acceptation</fullName>
            </value>
            <value>
                <fullName>Délai de traitement contrat</fullName>
            </value>
            <value>
                <fullName>Demande de paiement RAC</fullName>
            </value>
            <value>
                <fullName>Demande de renseignements compta</fullName>
            </value>
            <value>
                <fullName>Demande de traitement</fullName>
            </value>
            <value>
                <fullName>Demande info</fullName>
            </value>
            <value>
                <fullName>Démarches carte grise</fullName>
            </value>
            <value>
                <fullName>Divers</fullName>
            </value>
            <value>
                <fullName>Documents de cession</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Produit_financier__c.field-meta.xml
<CustomField>
    <fullName>Produit_financier__c</fullName>
    <formula>TEXT(Contrat__r.Produit_financier__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produit financier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Gestion_d_impay.recordType-meta.xml
<RecordType>
    <fullName>Gestion_d_impay</fullName>
    <active>true</active>
    <businessProcess>FR_DefaultSupportProcess</businessProcess>
    <label>Gestion d’impayé</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact_Client.recordType-meta.xml
<RecordType>
    <fullName>Contact_Client</fullName>
    <active>true</active>
    <label>Contact Client</label>
</RecordType>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contrat</label>
    <nameField>
        <label>Nom</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contrats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Code_statut_contrat__c.field-meta.xml
<CustomField>
    <fullName>Code_statut_contrat__c</fullName>
    <description>Code du statut du contrat</description>
    <label>Code statut contrat</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Compte_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Compte_client_associe__c</fullName>
    <label>Compte client associé</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contrats Client</relationshipLabel>
    <relationshipName>ContratsClient</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Contact_client_associe__c.field-meta.xml
<CustomField>
    <fullName>Contact_client_associe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact client associé</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contrats (Contact client associé)</relationshipLabel>
    <relationshipName>Contrats1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Date_de_l_alerte__c.field-meta.xml
<CustomField>
    <fullName>Date_de_l_alerte__c</fullName>
    <description>Date de l&apos;alerte</description>
    <label>Date de l&apos;alerte</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Numero_de_contrat__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_contrat__c</fullName>
    <externalId>true</externalId>
    <label>Numéro de contrat</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Produit_financier__c.field-meta.xml
<CustomField>
    <fullName>Produit_financier__c</fullName>
    <label>Produit financier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Crédit</fullName>
            </value>
            <value>
                <fullName>Crédit Bail</fullName>
            </value>
            <value>
                <fullName>LLD</fullName>
            </value>
            <value>
                <fullName>LOA</fullName>
            </value>
            <value>
                <fullName>CRE</fullName>
            </value>
            <value>
                <fullName>CRV</fullName>
            </value>
            <value>
                <fullName>ASV</fullName>
            </value>
            <value>
                <fullName>CRB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchContratCaseCampaignClose_TEST.cls
@IsTest
public class BatchContratCaseCampaignClose_TEST {
      @isTest static void TestBatchclose() {
        Recordtype rtaccid=[select id,DeveloperName from recordtype where DeveloperName='ClientB2B' limit 1 ];
        Recordtype rtcontid=[select id,DeveloperName from recordtype where DeveloperName='Contact_Client' limit 1 ];
        Recordtype impRecordTypeId=[select id,DeveloperName from recordtype where DeveloperName='Gestion_d_impay' limit 1 ];    
       //créer le compte B2B
         Account accou = new Account();
         accou.Name='TestBatcheclose';
         accou.RecordTypeId=rtaccid.id;
         insert accou;
      
      //créer le contact 
         Contact conta = new Contact();
         conta.FirstName='Contact';
         conta.LastName='batchclose';
         conta.RecordTypeId=rtcontid.id;
         conta.AccountId= accou.id; 
         insert conta;
          
          //créer le contrat
      List < Contract__c > insertcontra = new List< Contract__c >(); 
         Contract__c ctra = new Contract__c();
         ctra.Name='12341212LLD';
         ctra.Code_statut_contrat__c='RECAMIT';
         ctra.Compte_client_associe__c =accou.ID;
         ctra.Contact_client_associe__c = conta.Id;
         ctra.Produit_financier__c = 'LLD';
         ctra.Numero_de_contrat__c='12341212LLD';
         ctra.Date_de_l_alerte__c= date.parse('09/04/2022');     
         insertcontra.add(ctra);
          
           insert insertcontra;
          
          //créer le case
       
         Case cas = new Case();
         Database.DMLOptions dmo = new Database.DMLOptions();
         dmo.assignmentRuleHeader.useDefaultRule = true;
         cas.setOptions(dmo);
         cas.Subject = 'ctra Test';  
         cas.RecordTypeId=impRecordTypeId.id;   
         cas.Date_d_ch_ance__c= date.parse('04/04/2022'); 
         cas.Status ='A traiter';
         cas.Contrat__c = ctra.id;
         cas.AccountId= ctra.Contact_client_associe__r.AccountId;
         cas.ContactId=  ctra.Contact_client_associe__c;
         cas.Priority = 'Low';
         cas.Origin = 'Email'; 
         cas.Equipe__c = 'Acceptation Annexes';
         cas.Motif__c = 'Divers';
        
         insert cas;
      
          Test.startTest();
            BatchContratCaseCampaignClose obj = new BatchContratCaseCampaignClose();
            DataBase.executeBatch(obj);
        Test.stopTest(); 
    }
}