force-app/main/default/objects/Account/fields/BERs__c.field-meta.xml
<CustomField>
    <fullName>BERs__c</fullName>
    <label>BERs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BER__c/BER__c.object-meta.xml
<CustomObject>
    <label>BER</label>
    <nameField>
        <label>Code BER</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BERs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BER__c/fields/Compte_partenaire_associe__c.field-meta.xml
<CustomField>
    <fullName>Compte_partenaire_associe__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Compte partenaire associe</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BERs</relationshipLabel>
    <relationshipName>BERs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SM001_AccountServices.cls
public class SM001_AccountServices {
    @future
    public static void computeBERsField (set<Id> accountIds){
                        System.debug(accountIds);

        List<Account> accounts = [SELECT  Id,BERs__c, (Select name from BERs__r order by name DESC) From account where Id IN :accountIds];
                System.debug(accounts);

        for(Account a : accounts){
            a.BERs__c='';
            for(BER__c b :  a.BERs__r)
             IF(!a.BERs__c.contains(b.Name)) 
      a.BERs__c+=b.Name +' ';
        }
        
        update accounts;
    }
}