force-app/main/default/objects/DU_ContractOffer__c/DU_ContractOffer__c.object-meta.xml
<CustomObject>
    <label>Contract Offer</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Contract Offer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/DU_ContractOffer__c/fields/DU_Product__c.field-meta.xml
<CustomField>
    <fullName>DU_Product__c</fullName>
    <label>Product</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/DU_ContractOffer__c/fields/DU_TransactionId__c.field-meta.xml
<CustomField>
    <fullName>DU_TransactionId__c</fullName>
    <externalId>true</externalId>
    <label>Transaction Id</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerHandlerTest.cls
@Istest
public class ContentDocumentLinkTriggerHandlerTest {
    @Istest
    public static void testContentDocLink(){
        DU_ContractOffer__c conOffer = new DU_ContractOffer__c();
        conOffer.DU_Product__c = 'skodaserviceinspection';
        conOffer.DU_TransactionId__c = '91c6426e-dcc6-4164-be86-b92f87a26193';
        Insert conOffer;
        
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        insert contentVersion; 
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        List<ContentDocumentLink> ContentDocumentLinkList = new List<ContentDocumentLink>();
        ContentDocumentLink contentDocLink = new ContentDocumentLink();
        contentDocLink.LinkedEntityId = conOffer.Id;
        contentDocLink.ContentDocumentId = documents[0].Id;
        contentDocLink.shareType = 'V';
        contentDocLink.visibility = 'AllUsers';
        ContentDocumentLinkList.add(contentDocLink);
        Insert ContentDocumentLinkList;
    }
}