force-app/main/default/objects/Contact/fields/OptinQuestionnaireSatisfaction__c.field-meta.xml
<CustomField>
    <fullName>OptinQuestionnaireSatisfaction__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Si la case est coché, elle permettra au contact de recevoir l&apos;enquête de satisfaction.</inlineHelpText>
    <label>Opt-in Questionnaire Satisfaction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SM001_ContactServices_Test.cls
@isTest
public class SM001_ContactServices_Test {
    @isTest
    public static void SurveyOptOut(){
        Contact c = new Contact(LastName='Test Contact',UID__c='UidTestClass00xCap',OptinQuestionnaireSatisfaction__c=true);
        insert c;
        SM001_ContactServices.clearOptOutField('UidTestClass00xCap');
        SM001_ContactServices.clearOptOutField('UidTestClass00xCap1');
        System.assertEquals(false,[Select OptinQuestionnaireSatisfaction__c from Contact WHERE UID__c='UidTestClass00xCap'][0].OptinQuestionnaireSatisfaction__c,'The OptinQuestionnaireSatisfaction__c field was not updated');  
   }

    @isTest
    public static void SurveyOptOutEmptyString(){
        Contact c = new Contact(LastName='Test Contact',UID__c='UidTestClass00xCap',OptinQuestionnaireSatisfaction__c=true);
        insert c;
        String emptyField;
        SM001_ContactServices.clearOptOutField(emptyField);
   }

}