force-app/main/default/objects/Contact/fields/OptinQuestionnaireSatisfaction__c.field-meta.xml
<CustomField>
    <fullName>OptinQuestionnaireSatisfaction__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Si la case est coché, elle permettra au contact de recevoir l&apos;enquête de satisfaction.</inlineHelpText>
    <label>Opt-in Questionnaire Satisfaction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UID__c.field-meta.xml
<CustomField>
    <fullName>UID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>UID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CryptageContactUID_Test.cls
@isTest
public class CryptageContactUID_Test {
    static final String UIDCONTACT='uidcontactid';
    @isTest
    public static void encrypt(){
       List<id> listcont= new List<id>();
        Contact c = new Contact(LastName='Test Contact',UID__c=UIDCONTACT,OptinQuestionnaireSatisfaction__c=true);
        insert c;
        listcont.add(c.id);
        CryptageContactUID.encrypt(listcont);
        SurveyOptout.clearOptOutField(UIDCONTACT);
 }

}